### ISSUE TITLE
Docs not scrollable (v4 alpha)

### ISSUE THREAD

**Issue by alexkrolick** [ReactTraining/react-router#3927] opened 2016-09-22 03:32 UTC
The docs linked in the v4 alpha README are not scrollable: 

https://react-router-website-xvufzcovng.now.sh/

Removing height:100% fixes it

<img width="205" alt="screen shot 2016-09-21 at 8 30 35 pm" src="https://cloud.githubusercontent.com/assets/1571667/18736287/6b1ebcda-803a-11e6-939b-571c35f6aea0.png">

**Comment by adrianblynch** [comment] 2016-09-22 08:26
A dupe of https://github.com/ReactTraining/react-router/issues/3859?

**Comment by ryanflorence** [comment] 2016-09-22 14:01
react-router.now.sh

**Closed** 2016-09-22 15:57 UTC
