### ISSUE TITLE
React.StrictMode generates several warnings about the use of lifecycle functions

### ISSUE THREAD

**Issue by georgiosd** [ReactTraining/react-router#6095] opened 2018-04-17 06:37 UTC
Hey guys! 

Just wondering if there are plans to resolve React.StrictMode warnings about use of the now-old lifecycle methods.

Thanks

**Comment by timdorr** [comment] 2018-04-17 12:59
Dupe of #6060

**Closed by timdorr** 2018-04-17 12:59 UTC
