### ISSUE TITLE
Prop "path" of <Route /> should accept string, array of string and regex

### ISSUE THREAD

**Issue by shinima** [ReactTraining/react-router#4856] opened 2017-03-28 14:31 UTC
As the [doc](https://reacttraining.com/react-router/web/api/Route/path-string) said: 
> \<Route\>
> path: string  
> Any valid URL path that path-to-regexp understands.

And [path-to-regexp](https://github.com/pillarjs/path-to-regexp#usage) can accept:
> An Express-style string, an array of strings, or a regular expression.

So I think \<Route \> should accept array and regex.

## Version
4.0.0

## Steps to reproduce

Write code like:
` <Route path={['foo', 'bar']} component={MyComponent} />`

## Expected Behavior
No error. No warning.

## Actual Behavior
![image](https://cloud.githubusercontent.com/assets/5550931/24410626/228732a8-1406-11e7-9aa2-8d970e633ff8.png)

**Comment by timdorr** [comment] 2017-03-28 15:44
Dupe of #4551.

**Closed by timdorr** 2017-03-28 15:44 UTC
