### ISSUE TITLE
Inline JSX comments

### ISSUE THREAD

**Issue by Aprillion** [ReactTraining/react-router#4808] opened 2017-03-22 10:09 UTC
## Version
4.0.0, 4.0.0-beta.8
(worked fine in 4.0.0-beta.7)

## Test Case
N/A

## Steps to reproduce
1. works fine for:
```
  <Router>
    <Switch>
      <Route render={() => <div>gg</div>} />
      {/* comment */}
    </Switch>
  </Router>
```

2. move JSX comment to the same line
```
  <Router>
    <Switch>
      <Route render={() => <div>gg</div>} /> {/* comment */}
    </Switch>
  </Router>
```
=> `Uncaught TypeError: Cannot read property 'path' of undefined  at Switch.js:53` in Chrome
=> `TypeError: _element$props is undefined` in Firefox

3. remove Switch (I was trying to remove random bits when debugging):
```
  <Router>
    <Route render={() => <div>gg</div>} /> {/* comment */}
  </Router>
```
=> `Uncaught Error: A <Router> may have only one child element  at invariant (browser.js:40)` in Chrome and Firefox

4. works fine again when comment is on separate line:
```
  <Router>
    <Route render={() => <div>gg</div>} />
    {/* comment */}
  </Router>
```

## Expected Behavior
Renders without problems when using inline JSX comments.

## Actual Behavior
Random TypeError and does not render.

**Comment by pshrmn** [comment] 2017-03-22 15:08
The problem isn't the comment, it is the space.

If we go to https://babeljs.io/repl/, we can generate the `createElement` statements that the breaking code creates and we will see that:

```js
<Switch>
  <Route render={() => <div>gg</div>} /> {/* comment */}
</Switch>
// transform into
return React.createElement(
  Switch,
  null,
  React.createElement(Route, { render: function render() {
      return React.createElement(
        "div",
        null,
        "gg"
      );
    } }),
  " "
);
```

**Comment by pshrmn** [comment] 2017-03-22 16:50
Oh, I just noticed that #4746 was added after `4.0.0`. This will be included in the next patch/minor release.

**Closed by pshrmn** 2017-03-22 16:50 UTC
