### ISSUE TITLE
using the new context provider from react 16.3 breaks the router

### ISSUE THREAD

**Issue by bogdansoare** [ReactTraining/react-router#6072] opened 2018-04-08 09:14 UTC
## Version
4.2.2

## Test Case
https://codesandbox.io/s/rjl08qoxlp

## Steps to reproduce
Use a context provider inside the router component

## Expected Behavior
Using the new context provider should not break the router.

## Actual Behavior
Using the new context provider is breaking the router.

**Comment by pshrmn** [comment] 2018-04-08 15:38
It looks like this is only an issue if the router and context provider elements are created in the same render call. It isn't immediately clear in my mind why this is the case.

```jsx
// does not work
const One = () => (
  <Router>
    <Context.Provider>
      <Route />
    </Context.Provider>
  </Router>
);
ReactDOM.render(<One />, ...);

// does not work
const Two = () => (
  <Route />
);
ReactDOM.render((
  <Router>
    <Context.Provider>
      <Two />
    </Context.Provider>
  </Router>
), ...);

// works
const Three = () => (
  <Context.Provider>
    <Route />
  </Context.Provider>
);
ReactDOM.render((
  <Router>
    <Three />
  </Router>
), ...);
```

**Comment by gaearon** [comment] 2018-04-08 16:31
Might be related? https://github.com/facebook/react/issues/12551

**Comment by pshrmn** [comment] 2018-04-08 16:42
Will track via the React issue. For the time being, anyone running into this issue should just render the router and context provider separately.

**Comment by dantman** [comment] 2018-04-10 18:57
I'm having an issue with Routes not updating when my hash/path changes. Which may be this issue.

However while I am using the new context system, I do not think this is an issue specific to the new context system. As I see the following in the script. The old context system was **never** reliable enough to expect that context would be updated, the moment you try to use PureRender/shouldComponentUpdate to make your application run efficiently the old context system falls apart. Everyone using the old context system was expected to only pass static data down through context, if dynamic data was desired the accepted pattern was to pass down some sort of static observer so the consumers could subscribe instead of expecting context to be updated.

```js
  Router.prototype.getChildContext = function getChildContext() {
    return {
      router: _extends({}, this.context.router, {
        history: this.props.history,
        route: {
          location: this.props.history.location,
          match: this.state.match
        }
      })
    };
  };
```

I do not believe this is something that is React's job to fix, `getChildContext` is after all part of an experimental feature that was never considered stable and is now obsolete now that we have a new context system. IMHO in this case this is a bug that is react-router's responsibility, in this case the fix is to update to use the new context API. If you want support for React 16.2, there is a `create-react-context` polyfill library.

**Comment by timdorr** [comment] 2018-04-10 19:08
@dantman See this for a better explanation of what's going on: https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/guides/blocked-updates.md

**Comment by dantman** [comment] 2018-04-10 19:28
@timdorr Sounds exactly like what I thought. This is a react-router bug, the update behaviour of the old context API should never have been relied on. react-router should have been passing a subscriber down or using a 3rd party context wrapper that does so. Not expecting the old context API to update data and writing a long explainer on how to workaround the issue.

I'm not going to pepper my codebase with workarounds because react-router is not using context correctly. I guess I'm just going to have to abandon react-router until it starts using the new context API.

**Comment by brianespinosa** [comment] 2018-04-10 20:29
> I'm not going to pepper my codebase with workarounds because react-router is not using context correctly.

Unfortunately this is what we had to do in our large application. We did not realize until too late in the refactor to the latest RR version that this was a problem. Luckily we were able to make a HOC that we swapped out all Link components with that uses redux to do this instead.

**Comment by CyrusZei** [comment] 2018-04-19 08:50
any updates on this ?

**Comment by CyrusZei** [comment] 2018-04-19 11:05
I dont know, but would it be nice if you could merge the PrivateRoute component that are in the docs ?
so that you could do something like this 
`import {PrivateRoute} from "react-router-dom";`

and maybe add a prop to the PrivateRoute isAuthed ? 
This might be a step back to router v3 "onEnter", but what else will you use the PrivateRoute component for if not Auth ?

For me the PrivateRoute is boiler code that you need to enter everytime you need auth.

This is just a tought on how the PrivateRoute component could look like
`<PrivateRoute isAuthed={this.state.isAuthed} redirect={'/login'} to={'/dashboard'} data={context API} />`

so you need to wrap the context api around the PrivateRoute. 
This is just a thought 😄

**Comment by renatonmendes** [comment] 2018-04-25 23:06
@brianespinosa  Can you please share with us how you´ve solved that ? I need to use the context provider with routing without success.

**Comment by brianespinosa** [comment] 2018-04-30 18:01
@renatonmendes we had to create our own Webpack plugin that replaces our use of the `react-router-dom` package with a custom implementation where we store a location key in Redux. Once React Router is updated to support the proper use of the new context API, we simply remove our plugin and it goes back to using the real `react-router-dom` package as normal.

Past this explanation, unfortunately I cannot share any code with you from my current project.

**Comment by mrbinr** [comment] 2018-05-03 13:07
Hi,
I have modified first code from @bogdansoare and it seems to works now : [https://codesandbox.io/s/xon5z2nk9z](https://codesandbox.io/s/xon5z2nk9z)

**Comment by szagi3891** [comment] 2018-05-24 02:56
This problem still exists in my project (reacta version 16.4). It occurs in such a case:

```
        ReactDOM.render((
            <ApolloProvider client={client}>
                <BrowserRouter>
                    <AppWithRouter />
                </BrowserRouter>
            </ApolloProvider>
        ), root);
```

**Comment by gaearon** [comment] 2018-05-24 20:10
Can you provide a new small reproducing case? Ideally without any third party libs, just React.

**Comment by timdorr** [comment] 2018-06-06 19:37
This should be fixed in 16.4, so I'm closing this out.

**Closed by timdorr** 2018-06-06 19:37 UTC

**Comment by Martsyalis** [comment] 2018-06-08 22:20
@szagi3891 did you add WithRouter to your Context Component? That solved it for me with 16.4

**Comment by johannessteu** [comment] 2018-06-15 08:34
@Martsyalis just like this?
```
import React from 'react';
import { withRouter } from 'react-router'

const AppContext = React.createContext();

export default withRouter(AppContext);

```

Does not work for me actually >.>

**Comment by szagi3891** [comment] 2018-06-15 16:36
@Martsyalis
Yes, I used this function this way:

```
        const AppWithRouter = withRouter(() => <App />);

        ReactDOM.hydrate((
            <ApolloProvider client={client}>
                <BrowserRouter>
                    <AppWithRouter />
                </BrowserRouter>
            </ApolloProvider>
        ), root);
```
Then the react-router started to work properly.

**Comment by Martsyalis** [comment] 2018-06-15 21:42
withRouter should be used on every component that relies on history or match props. So everything that listens to url.
