### ISSUE TITLE
Scrolling issues with documentation for react-router v4

### ISSUE THREAD

**Issue by velopert** [ReactTraining/react-router#3868] opened 2016-09-15 20:59 UTC
Pages for including home, quick start, and api pages like browser router.. to redirect are not scrollable.
I have tested it in chrome, firefox, and ie. none of the browser show the scrollbar at the right.

So only way to read the contents was to do this: 
![57](https://cloud.githubusercontent.com/assets/17202261/18567346/b84b7f78-7bd2-11e6-98eb-58e9fedd8571.png)
Zoooming out. hehehehe

It's not an urgent issue, but hope it gets fixed soon.

**Comment by timdorr** [comment] 2016-09-16 00:53
Dupe of #3859.

**Closed by timdorr** 2016-09-16 00:53 UTC
