### ISSUE TITLE
[v4] Link's rerendering on naviagte

### ISSUE THREAD

**Issue by mbrevda** [ReactTraining/react-router#4017] opened 2016-10-09 09:14 UTC
Based on output from [why did you update](https://github.com/garbles/why-did-you-update), it would seems all `Link`'s are rerendered on nagivate. If their active state didn't change, might this be avoidable?

<img width="850" alt="screen shot 2016-10-09 at 12 11 06 pm" src="https://cloud.githubusercontent.com/assets/293004/19219363/d832ad08-8e19-11e6-96a7-c8aa0f715079.png">

**Comment by timdorr** [comment] 2016-10-09 15:00
Dupe of #3985, and there is a PR open for it: #3986

**Closed by timdorr** 2016-10-09 15:00 UTC

**Comment by mbrevda** [comment] 2016-10-10 09:01
Thanks. The PR addresses links that are active agnostic. What about those that aren't - is there anything to prevent them from rerendering when their active state doesn't update?
