### ISSUE TITLE
Redundant imports from history bloating bundle sizes

### ISSUE THREAD

**Issue by DullReferenceException** [ReactTraining/react-router#5971] opened 2018-02-26 18:25 UTC
## Version
`react-router-dom@4.2.2`

## Steps to reproduce
Create a webpack bundle that import `react-router-dom`

## Expected Behavior
Only the main or `es` folder of the `history` library is bundled

## Actual Behavior
Both the main and `es` folder of the `history` library is bundled

## Theory
I believe that the issue stems from the fact that there are two different ways that things are being imported from history:

* Deep imports like `require('history/createBrowserHistory')`
* Direct imports like `require('history')`

The former type of import is bringing in JS modules in the root of `node_modules/history`, but the latter type is causing `node_modules/es/index.js` and its dependencies to be brought in due to the `"main"` entry point in its package.json.

In theory changing the imports to be consistent will avoid bundling all the files in both `node_modules/history` and `node_modules/history/es`.

**Comment by pshrmn** [comment] 2018-02-26 18:36
This is a duplicate of #5576, which was fixed with #5589 but is not yet released.

**Closed by pshrmn** 2018-02-26 18:36 UTC
