### ISSUE TITLE
pushState method works with full URLs only

### ISSUE THREAD

**Issue by ybelenko** [ReactTraining/react-router#4119] opened 2016-10-30 15:59 UTC
I'm dissapointed with pushState method right now. It says that I can use full urls only.
Let's imagine I have multistep form and I have routes

``` javascript
<Route path="/" component={ App }
    <Route path="companies" companent={ CompanyPage }>
        <Route path="feedback/:stepName" component={ MultiStepForm } />
    </Route>
    <Route path="staff" component={ StaffPage }>
        <Route path="feedback/:stepName" component={ MultiStepForm } />
    </Route>
</Route>
```

In this scenario when user clicks "continue" button in the form I need to change url from `.../feedback/step_one` to `.../feedback/step_two`, but I don't know in which route(`companies` or `staff`) user is located. 
It would be very convenient to change last part of the url by calling `pushState(null, "step_two")` instead of parsing and replacing current url manually. If I understand correct, main goal of **react-router** is to avoid manual URL parsing, so there should be way to change URL partially.

**Comment by timdorr** [comment] 2016-10-31 15:08
Dupe of #2172

**Closed by timdorr** 2016-10-31 15:08 UTC
