### ISSUE TITLE
[v6]: Unexpected behavior of useMatch() hook

### ISSUE THREAD

**Issue by PouRiaBG** [ReactTraining/react-router#7919] opened 2021-07-23 11:16 UTC
### What version of React Router are you using?

6

### Steps to Reproduce

Hello, I noticed unusual behavior while using useMatch hook.

### Expected Behavior

for example, useMatch ("/ about") should be matched when the URL is /about, which works as well as version five, but behaves differently when it is useMatch ("/ a / *"). Surprisingly, it matches again!!
I do not know if this is a bug or if useMatch is supposed to behave differently in version 6.

### Actual Behavior

 Here is code sandbox for more information : 
https://codesandbox.io/s/react-router-basic-forked-ou8c3?file=/example.js
 checkout log when route is /about.

**Comment by timdorr** [comment] 2021-07-24 03:25
Duplicate of #7529

**Closed by timdorr** 2021-07-24 03:25 UTC
