### ISSUE TITLE
React-router v4 with React v15.5.0 gives warning about PropTypes

### ISSUE THREAD

**Issue by katsos** [ReactTraining/react-router#4937] opened 2017-04-08 20:41 UTC
React throws a warning about the use of React.PropTypes.
https://facebook.github.io/react/docs/typechecking-with-proptypes.html

## Version
react v15.5.0
react-router v4.0.0

## Test Case
http://codepen.io/nikoskeyz/pen/BWgbwq

## Steps to reproduce
Just import react-router in your React v15.5.0 project

## Expected Behavior
No warnings.
## Actual Behavior
Console warning: `Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.`

**Comment by YasserKaddour** [comment] 2017-04-08 20:48
There is two PR for this already #4933 #4934 :smile:

**Comment by timdorr** [comment] 2017-04-09 17:51
Should be fixed on master. I'll see about getting a release out soon.

**Comment by Spy-Seth** [comment] 2017-04-11 08:33
The patch has been release [on the v3.x branch](https://github.com/ReactTraining/react-router/releases/tag/v3.0.4). Is there an issue that block the v4 branch to be patched too?

**Comment by timdorr** [comment] 2017-04-11 13:36
Yep, [there's an issue with granting me publish access](https://github.com/npm/npm/issues/16233), otherwise I would do it 😄

**Closed by timdorr** 2017-04-11 13:36 UTC

**Comment by ryancogswell** [comment] 2017-04-12 16:36
withRouter.js is still importing PropTypes from react instead of prop-types.

**Comment by timdorr** [comment] 2017-04-12 17:51
Yes, I'll do a cleanup release for this soon. We merged some PRs built before 15.5 was released.

**Comment by raffjones** [comment] 2017-05-17 11:02
Hi @timdorr - thanks for the update. Any news on this? I'm seeing this issue having just upgraded to v4. Not hugely worried about it but was wondering if there's a branch where it’s been fixed.

**Comment by ryancogswell** [comment] 2017-05-17 14:39
Hi @raffjones - this was fixed for me with a release within a couple days of timdorr's comment. Are you sure the warning is being caused by react-router?

**Comment by raffjones** [comment] 2017-05-17 14:45
@ryancogswell Yes - I traced the error back in the console. Just before the warning function is called, I see:

`BrowserRouter.propTypes = {
  basename: __WEBPACK_IMPORTED_MODULE_0_react__["PropTypes"].string,
  forceRefresh: __WEBPACK_IMPORTED_MODULE_0_react__["PropTypes"].bool,
  getUserConfirmation: __WEBPACK_IMPORTED_MODULE_0_react__["PropTypes"].func,
  keyLength: __WEBPACK_IMPORTED_MODULE_0_react__["PropTypes"].number,
  children: __WEBPACK_IMPORTED_MODULE_0_react__["PropTypes"].node
};`

And `__WEBPACK_IMPORTED_MODULE_0_react__` is effectively `React`

**Comment by raffjones** [comment] 2017-05-17 15:04
@ryancogswell Thanks for the steer. I looked in the source code, and saw the import statement was indeed referencing `prop-types` so thought it must be related to whatever version I had pulled down from npm. Looking in my `package.json` file I saw: `"react-router-dom": "^4.0.0-beta.8"` - have changed this to the latest (4.1.1).

Now I'm getting `Unexpected token )` error, triggered by:

    if (prevStateLevel) {
      if (colors.prevState) {
        logger[prevStateLevel](
          '%c prev state',
          `color: ${colors.prevState(prevState)}; font-weight: bold`,
          prevState,
        );
      } else logger[prevStateLevel]('prev state', prevState);
    }

(dangling comma after `prevState` in the parentheses.

**Comment by graemebenzie** [comment] 2017-05-25 10:59
I'm seeing the warning. I started with create-react-app and im following this tutorial https://egghead.io/lessons/react-run-the-react-router-v4-examples-with-create-react-app

package.json
```
    "react": "^15.5.4",
    "react-dom": "^15.5.4",
    "react-router-dom": "^4.0.0-beta.8"
```

App.js
```
import React from 'react'

import { BrowserRouter } from 'react-router-dom'

const App = () => <h1>Hello World</h1>

export default App
```

If I comment out 
import { BrowserRouter } from 'react-router-dom'

The warning disappears

**Comment by ryancogswell** [comment] 2017-05-25 15:43
@graemebenzie You just need to update your package.json to point at the most recent version ("^4.1.1" instead of "^4.0.0-beta.8".

**Comment by graemebenzie** [comment] 2017-05-26 07:09
Ah, great thank you. Installed with @next and then didnt pay attention to
the version.

**Comment by pshrmn** [comment] 2017-05-26 17:16
@timdorr the `@next` tags should probably be updated/removed for the core and dom packages. 
```sh
$ npm dist-tag ls react-router
latest: 4.1.1
next: 4.0.0
previous: 3.0.5
$ npm dist-tag ls react-router-dom
latest: 4.1.1
next: 4.0.0-beta.8
```

**Comment by timdorr** [comment] 2017-05-26 17:19
Oof, yeah. I'll get rid of them.

**Comment by victorredondoGL** [comment] 2017-06-08 19:32
I'm getting the warning at 4.1.1

**Comment by ryancogswell** [comment] 2017-06-08 20:03
@victorredondoGL Are you sure the warning is coming from react-router and not some other package? If it is react-router, please include the stack trace to show which part of react-router is causing the warning.

**Comment by bgmort** [comment] 2017-06-22 00:55
I can second @victorredondoGL.  Using 4.1.1, I get PropTypes warnings.  If I remove all traces of react-router, the errors are gone.  I can see traces pointing to Router, Route, and Link.

**Comment by ryancogswell** [comment] 2017-06-22 16:15
@bgmort and @victorredondoGL -- I'm still skeptical since I am also using 4.1.1 and not seeing the warnings and I've looked through the 4.1.1 router code and it is using the new "prop-types" package. I'll give you the benefit of the doubt and assume that you have verified that you are indeed using 4.1.1 and not an older version, but if that is the case and if the warnings are showing traces pointing at Router, Route, and Link then you have some other package that you are pulling in that is in turn pulling in an old version of react-router. I would recommend doing a search for "router" within your node_modules to see if any of your other modules have their own copy of an older react-router version that they are pulling in (should also be able to determine the package pulling it in via the warning trace). Please post the full warning trace if you still think this is coming from react-router 4.1.1.

**Comment by yhaiovyi** [comment] 2017-11-20 21:31
`react-router-dom@4.2.2/umd/react-router-dom.js` lines 262, 1872. I think it's made for backward compatibility, but you can check if React.PropTypes is getter and don't touch it then. This warning is really annoying.

**Comment by victorredondoGL** [comment] 2017-11-20 22:11
@ryancogswell sorry for the late response, I was wrong; the warning was due to another third-party, I'm working with RR 4.2.2 and there is no sign of the warning any more.

**Comment by ryancogswell** [comment] 2017-11-20 23:09
@yhaiovyi You're looking at one of the build outputs for react-router-dom. "master" doesn't have this code because the code you're referencing is Facebook code from the 'prop-types' package:
https://github.com/facebook/prop-types/blob/master/checkPropTypes.js

This code is included in umd/react-router-dom.js because the react-router code imports the 'prop-types' package. I am not using the umd files, but rather importing the specific exported objects (Route, Link, etc.) from react-router-dom and then using npm/webpack (an ejected create-react-app setup) to build my JS app, so I'm less familiar with the considerations that come into play when using the umd files, but I believe the warning you're receiving would just indicate that prop-types are being used inappropriately - the fact that the warning seems to come from react-router-dom code is just because of it pulling in the Facebook code -- not because react-router is causing the issue.

**Comment by VladLegkowski** [comment] 2017-12-19 14:40
Updating `node -v` resolved issue for me

**Comment by Bosch-Eli-Black** [comment] 2018-03-16 02:15
I just ran into this issue. For me, the problem was that I had an outdated version of react-dom alongside a new version of react-router-dom and importing from 'react-dom' instead of 'react-router-dom'.
