### ISSUE TITLE
ReferenceError: Element is not defined

### ISSUE THREAD

**Issue by fedorovsky** [ReactTraining/react-router#6610] opened 2019-03-02 10:26 UTC
/react-router-dom/cjs/react-router-dom.js:209
    current: PropTypes.instanceOf(Element)

ReferenceError: Element is not defined

Version: 4.4.0-beta.7

**Comment by pshrmn** [comment] 2019-03-02 13:40
Fixed by #6607

**Comment by timdorr** [comment] 2019-03-03 00:13
Just merged that in. Should be released soonish.

**Closed by timdorr** 2019-03-03 00:13 UTC

**Comment by TotallWAR** [comment] 2019-03-06 07:53
Is this fix in new version?
I can't see it fixed in version 4.4.0-beta.7 when install it with npm.

**Comment by taime** [comment] 2019-03-12 05:22
It's **NOT FIXED** in  4.4.0-beta.7!!!

**Comment by mattcarlotta** [comment] 2019-03-12 18:45
The issue is that `rollup` removes unused code. It considers adding `const Element = typeof Element === "undefined" ? function () {} : Element;` as unused and unneccesary for the compiled source. The issue eminates from this [line](https://github.com/ReactTraining/react-router/blob/master/packages/react-router-dom/modules/Link.js#L65): 

```
    PropTypes.shape({ current: PropTypes.any })
```
Using `PropTypes.any` seems to trigger a `PropTypes.instanceOf(Element)` validation call. Since `Element` is undefined, it crashes.  The solution is to either create a custom validation function to define the `shape` of the `current` prop or do a simple patch where `Element` is utilized and remains declared in the compiled output:

```
  const Element = typeof Element === "undefined" ? function() {} : Element;
  const innerRefType = PropTypes.oneOfType([
    PropTypes.string,
    PropTypes.func,
    PropTypes.instanceOf(Element), // by adding this line, rollup won't remove the "Element" declaration
    PropTypes.shape({ current: PropTypes.any })
  ]);
```

**Comment by wmertens** [comment] 2019-03-14 13:42
@timdorr we're 2 weeks on, any chance of a beta.8 that fixes this?
