### ISSUE TITLE
v6 release

### ISSUE THREAD

**Issue by y-nk** [ReactTraining/react-router#7827] opened 2021-04-22 03:45 UTC
Hello,

v6 beta was released a year ago, but there's no release of a stable version yet. Is there any plan or roadmap concerning the offficial release of the v6 ?

Thanks,

**Comment by pshrmn** [comment] 2021-04-22 05:31
Duplicate of https://github.com/ReactTraining/react-router/issues/7613

**Closed** 2021-04-22 05:31 UTC
