### ISSUE TITLE
Stateless function components cannot have refs.

### ISSUE THREAD

**Issue by Saifu0** [ReactTraining/react-router#6937] opened 2019-09-26 17:30 UTC
After applying Route and Link I am facing this problem.
Stateless function components cannot have refs.
![Screenshot from 2019-09-26 21-43-49](https://user-images.githubusercontent.com/43892879/65710838-6338a280-e0b1-11e9-8de7-1c3d5727e702.png)

▶ 22 stack frames were collapsed.
./src/index.js
src/index.js:7
4 | import App from './App';
5 | import registerServiceWorker from './registerServiceWorker';
6 |

7 | ReactDOM.render( , document.getElementById( 'root' ) );
8 | registerServiceWorker();
9 |
10 |

**Comment by timdorr** [comment] 2019-09-26 19:29
Duplicate of #6934

**Closed by timdorr** 2019-09-26 19:29 UTC
