### ISSUE TITLE
[v6.0.0-beta.0] Deeply nested routes are not rendered

### ISSUE THREAD

**Issue by loun4** [ReactTraining/react-router#7458] opened 2020-06-27 16:16 UTC
## Version

v6.0.0-beta.0

## Expected Behavior

`<SupportDetails />` must be rendered inside `<Support />` through `<Outlet />`  when matching the path `/:userId/details`.

```javascript
    <Routes>
        <Route path="/:userId" element={<App />}>
          <Route path="/" element={<Support />}>
            <Route path="details" element={<SupportDetails />} />
          </Route>
        </Route>
    </Routes>
```

```
   // <Support />
    <div>
      <Outlet />
    </div>
```
## Actual Behavior

Nothing is rendered ...

Same issue #7239

**Comment by timdorr** [comment] 2020-06-28 20:55
Duplicate of #7239

**Closed by timdorr** 2020-06-28 20:55 UTC
