### ISSUE TITLE
react-router-redux missing ./selectors

### ISSUE THREAD

**Issue by halkeye** [ReactTraining/react-router#5637] opened 2017-10-18 20:35 UTC
## Version
5.0.0-alpha.7

(I couldn't get it working on codesandbox)
On our build jest is complaining it can't find module selectors.

```
  ● Test suite failed to run

    Cannot find module './selectors' from 'index.js'

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:179:17)
      at Object.<anonymous> (node_modules/react-router-redux/index.js:6:18)
```

Based on grepping i find:
node_modules/react-router-redux/index.js:var _selectors = require('./selectors');
but only the file exists:
node_modules/react-router-redux/es/selectors.js

**Comment by halkeye** [comment] 2017-10-18 20:36
I'm thinking https://github.com/ReactTraining/react-router/blob/master/packages/react-router-redux/package.json#L10 needs the files: {} block to include selectors.

**Comment by timdorr** [comment] 2017-10-19 00:31
Dupe of #5636

**Closed by timdorr** 2017-10-19 00:31 UTC
