### ISSUE TITLE
Lag provoked by useHistory

### ISSUE THREAD

**Issue by lapico** [ReactTraining/react-router#7000] opened 2019-10-21 13:32 UTC
## Version

"react-router-dom": "^5.1.2"

## Test Case

This simple effect causes the whole app to glitch.

Note that this code is perfectly independent from the rest of the code (page is not used anywhere else) and that this is not a case of infinite loop (effect runs one time just as expected)...

```
useEffect(() => {
  if (page) history.push(`/${page}`)
}, [page, history])
```

## Steps to reproduce

The app is a simple slide editor and some animations are triggered when navigating between slides.

I just want to update the url according to the current slide.

## Expected Behavior

Smooth animation as when history.push() is not called.

## Actual Behavior

A very perceptible lag is happening when the effect is uncommented.

It feels like some scheduling is delayed by the call to history.push() while updating the url should not have any impact on other react processes...

Probably same as #6999

Imperatively updating route causes a rerender. In most of my use cases, the other way around of updating the route based on app changes is more useful, but maybe I'm missing something...

**Comment by MeiKatz** [comment] 2019-10-21 14:06
I think it is because `history.push` mutates the `history` object, what forces `useEffect` to execute again. Therefore you create an infinity loop. Maybe you should split this into two `useEffect` hooks or you might drop `history` of your dependency list.

**Comment by lapico** [comment] 2019-10-21 15:16
@MeiKatz thanks for the quick answer !

I tried but it's not that. The problem is that history.push() triggers a rerender of the whole app.

**Comment by lapico** [comment] 2019-10-21 15:47
Before, I used successfully this trick :
https://github.com/ReactTraining/react-router/issues/6430#issuecomment-434515664

**Comment by timdorr** [comment] 2019-10-21 15:53
Yep, this is a duplicate of #6999

**Closed by timdorr** 2019-10-21 15:53 UTC

**Comment by lapico** [comment] 2019-10-21 16:41
Yes you are right, I tried to use this trick with the same effect.

I'll put back the useHistory hook and find how to make the app compliant with it...

Thanks !

**Comment by MeiKatz** [comment] 2019-10-21 17:45
Maybe the workaround described in #6999 is something for you ..
