### ISSUE TITLE
Route is not exported in react-router-dom

### ISSUE THREAD

**Issue by hasankhalid** [ReactTraining/react-router#6639] opened 2019-03-18 09:59 UTC
I am running a standard code via create-react-app and react-router-dom 4.4 and when i import Route and Switch from 'react-router-dom', the program fails to compile and i get an error that says "Attempted import error: 'Route' is not exported from 'react-router-dom'. 

My code right now is 

![Screen Shot 2019-03-18 at 3 02 41 PM](https://user-images.githubusercontent.com/20278920/54522376-e0f75500-498e-11e9-8b40-e30c60565fbc.png)

I am not sure what's happening but if anyone can help me figure out what i am doing wrong, that would be great.

**Comment by hasankhalid** [comment] 2019-03-18 09:59
`import React, { Component } from 'react';
import logo from './logo.svg';
import './App.css';
import { Route, Switch } from "react-router-dom";
import Login from './views/login';
import Home from './views/home';

class App extends Component {
  render() {
    return (
      <div className="App">
        <Switch>
          <Route exact path ="/" component={Login}/>
          <Route path ="/home" component={Home}/>
        </Switch>
      </div>
    );
  }
}

export default App;
`

**Comment by MeiKatz** [comment] 2019-03-18 10:09
Importing `<Route />` and `<Switch />` from `react-router-dom` is deprecated. Try to import it from `react-router` instead.

**Comment by StringEpsilon** [comment] 2019-03-18 10:15
@MeiKatz You sure that's not a bug? The changelog doesn't mention this and the react-router-dom index.js has this line right on top:

```js
export * from "react-router";
```

That seems to me like it's intended to re-export _all_ modules from react-router.

**Comment by MeiKatz** [comment] 2019-03-18 10:20
@StringEpsilon No, it's definitely the intended way to use it. Just take a look at the source of `react-router-dom/Route`: https://github.com/ReactTraining/react-router/blob/master/packages/react-router/Route.js#L2. Support for this way will be remove with v5.0 of React Router.

**But** I think it's a bug nevertheless because it should work, but with a deprecation warning.

**Comment by hasankhalid** [comment] 2019-03-18 10:22
That is what i was confused about. The changelog does not mention the deprecation and the documentation for react router still shows this code. It should at least show a deprecation warning if it does not work. 
![Screen Shot 2019-03-18 at 3 21 20 PM](https://user-images.githubusercontent.com/20278920/54523505-827fa600-4991-11e9-9dac-e103ddd7ce14.png)

**Comment by MeiKatz** [comment] 2019-03-18 10:27
@hasankhalid You're right and I am also not sure about the code policy here at React Router. When you look at the code here in the repository, then there is a deprecation warning defined. When I look at the compiled code in my `node_modules` folder, then there is not deprecation warning, what's weird.

Also I cannot reproduce your error. When I try to import `<Route />` from `react-router-dom` everything is fine (version is 4.4.0).

**Comment by StringEpsilon** [comment] 2019-03-18 10:30
@MeiKatz I thought that warning was just to avoid mixing CJS with ESM imports, as the [changelog of 4.4.beta.1](https://github.com/ReactTraining/react-router/releases/tag/v4.4.0-beta.1) says. I could not find any other evidence that importing ```react-router``` modules through ```react-router-dom``` is supposed to go away or deprecated. 

Back to topic: @hasankhalid Can you try to reproduce this issue in a separate repository? It seems like react-router 4.4 is quite sensible to different build environments, judging from other issues.

**Comment by hasankhalid** [comment] 2019-03-18 10:33
It was some weird behaviour that i did not not understand. I imported them via react-router and it was worked. I tried react-router-dom and the error showed again. I terminated the process and started it again and now it is working. I am not sure what was happening there but the issue is solved.

**Comment by Mydeen-SN** [comment] 2019-03-18 13:00
i am getting below error in my react application.
![Uploading image.png…]()

**Comment by Xazzzi** [comment] 2019-03-18 13:06
![image](https://user-images.githubusercontent.com/1200201/54531774-c7eea400-498e-11e9-9fb3-990269a871a1.png)
Seems like Route.propTypes are missing.

**Comment by Ankit895** [comment] 2019-03-18 13:49
<Link> stopped working

**Comment by Ankit895** [comment] 2019-03-18 13:53
<Link> stopped working after new changes

**Comment by timdorr** [comment] 2019-03-18 14:00
@Ankit895 See #6630. That doesn't sound like it relates to this issue.

**Comment by timdorr** [comment] 2019-03-22 11:44
This is a dupe of #6630. You have mixed versions of react-router and react-router-dom installed.

**Closed by timdorr** 2019-03-22 11:44 UTC

**Comment by SistemasSouza** [comment] 2019-03-26 14:06
I have the same problem, in import Route of the react-router-dom

my import 

![image](https://user-images.githubusercontent.com/13488005/55003395-1f0bfe80-4fb7-11e9-9b59-564dcb5a3142.png)

error message
![image](https://user-images.githubusercontent.com/13488005/55003428-2b905700-4fb7-11e9-8c76-acb5f1424db2.png)

the project was created with create-react-app

**Comment by hasankhalid** [comment] 2019-03-28 09:02
@timdorr is correct. The error occurs when you have mixed versions of react-router and react-router-dom installed.

**Comment by webwizart** [comment] 2019-03-29 21:02
Same issue here, generated with react-create-app
<img width="319" alt="Screenshot 2019-03-29 at 22 00 57" src="https://user-images.githubusercontent.com/527613/55262478-2872c080-526e-11e9-9648-0002c4c78add.png">

![Screenshot 2019-03-29 at 22 00 31](https://user-images.githubusercontent.com/527613/55262456-1a24a480-526e-11e9-9748-a4acdf8b073e.png)

Which version should I use then?

**Comment by robbertolierook** [comment] 2019-04-15 18:20
Same here,  also with create-react-app

```YAML
  "dependencies": {
    "react": "^16.8.6",
    "react-dom": "^16.8.6",
    "react-router": "^5.0.0",
    "react-router-dom": "^5.0.0",
    "react-scripts": "2.1.8"
  },
```
```js
import { BrowserRouter, Route, Switch } from 'react-router-dom';
```
```
./src/components/Router.js
Attempted import error: 'Route' is not exported from 'react-router-dom'.
```

**Comment by robbertolierook** [comment] 2019-04-15 18:41
Nvm fixed it, initially I only downloaded `react-router-dom`. When you do that it will crash because you obviously need `react-router` as well, so @webwizart and @SistemasSouza, install that too. After that it still won't work because you need to restart your development server. That should do it

**Comment by tusharmutreja** [comment] 2019-04-23 06:46
Close the server and restart it. It Works Fine
**yarn start**

**Comment by adewale2018** [comment] 2019-05-06 11:41
Hi all. I have the same issue as discussed above. I could only see that the issue has been solved with Nvm but don't actually understand how. Can anyone kindly be of assistance? Thanks

**Comment by enKoding** [comment] 2019-05-14 10:56
> Close the server and restart it. It Works Fine
> **yarn start**

This is the kind of person who would save the world if everything started to fail.
