### ISSUE TITLE
Provide propType definitions for Route

### ISSUE THREAD

**Issue by TomiS** [ReactTraining/react-router#4439] opened 2017-02-02 09:24 UTC
As someone who wants all proptypes to be strictly defined in a component, I'd propose a new convenience feature: predefined router proptypes shorthand for wrapped components.

```jsx
// MyRoutedComponent.js
import { routerPropTypes } from 'react-router';
// ... component code ...
MyRoutedComponent.propTypes = {
    ...routerPropTypes,
    foo: React.PropTypes.any,
    bar: React.PropTypes.node,
};
```
Thoughts?

ps. I'm willing to implement a PR if this idea is something you could consider.

**Comment by kwelch** [comment] 2017-02-02 14:04
These were removed to reduce package size. Additionally, explicitly naming the props you are using is a better practice, as propTypes should show what the component uses not everything that is passed to it.

**Comment by timdorr** [comment] 2017-02-02 15:48
Dupe of #4419.

**Closed by timdorr** 2017-02-02 15:48 UTC

**Comment by TomiS** [comment] 2017-02-02 15:50
Sounds reasonable. Sorry for duplicate issue.

**Comment by Wobbly-Wibbly** [comment] 2017-07-20 09:26
@TomiS  Hello, I'm using strict eslint rules for prop-types, so we had to define all the shapes.
I have created a package just for props, so those shapes are not duplicated all over the projects.
Thought maybe it would be helpful for you also.
https://www.npmjs.com/package/react-router-props
