### ISSUE TITLE
Feature Request: upgrade path-to-regexp

### ISSUE THREAD

**Issue by AprilArcus** [ReactTraining/react-router#7711] opened 2020-12-04 06:32 UTC
Newer versions of path-to-regexp has features of which I am envious, e.g. support for negative lookahead regular expressions. React Router is currently pinned to a very old version. If an upgrade presents a breaking change then 6.0 would be a good time to consider doing it.

**Comment by timdorr** [comment] 2020-12-04 16:17
Duplicate of #6899

**Closed by timdorr** 2020-12-04 16:17 UTC
