### ISSUE TITLE
Set matched routes on StaticRouter Context by default

### ISSUE THREAD

**Issue by cquillen2003** [ReactTraining/react-router#5476] opened 2017-08-29 22:57 UTC
I think StaticRouter Context should do more by default.  A url is set automatically if a <Redirect/> is rendered.  I would like to have an array of all components rendered via <Route/>s set automatically as well.

This would allow a straightforward data loading solution with server rendering WITHOUT needing a centralized, static route config.  I finally bought into the "Dynamic Routing" philosophy of V4 after watching one of Ryan and Michael's conference talks.  Now, I am getting into server-rendering and the guides call for a centralized, static route config!  At the least, I think the docs should show an example of server rendering (somehow) using the V4 philosophy.

Here is the use case I am thinking of:

```javascript
//Data loading with server rendering

//Inside a server request

var context = {};

//First, "pre-render" to determine data dependencies
ReactDOMServer.renderToString(<App url={req.url} context={context}/>);

var promises = [];

//Pull data dependencies from StaticServer Context
context.routes.forEach(route => {
    if (route.loadData) promises.push(route.loadData(route.match));
});

Promise.all(promises).then(data => {
    //Build data prop or redux store
    //Render again with data prop or redux store

    var html = ReactDOMServer.renderToString(<App url={req.url} data={data}/>);

    //Send to client
});
```

**Comment by timdorr** [comment] 2017-08-29 23:13
The "routes" concept from react-router-config isn't something exposed to staticContext. Nor should it be. All it could possibly know are what matches occurred, but those would be relatively useless without some sort of context. 

This is technically a dupe of #4962, which seems to run a function on each matched route to determine entry, but could also double as a preloading point.

**Closed by timdorr** 2017-08-29 23:13 UTC

**Comment by cquillen2003** [comment] 2017-08-29 23:40
@timdorr What I am proposing has nothing to do with react-router-config as I understand it.  On the contrary, it would be an alternative to using react-router-config or a hand-rolled route config array/object.  I am proposing a way to determine the matching routes/components in an app built without a centralized route config.

**Comment by pshrmn** [comment] 2017-08-29 23:48
The `context` object is just an object. You can do anything that you want with it. There is nothing stoppping you from doing something like this:
```js
class Thing extends React.Component {
  static contextTypes = {
    router: PropTypes.shape({
      staticContext: PropTypes.object
    })
  }
  
  load() {
    return fetch(...).then(resp => ...)
  }

  componentWillMount() {
    // this is only available when rendering on the server
    const { staticContext } = this.context.router;
    if (staticContext) {
      if (!staticContext.promises) {
        staticContext.promises = []
      }
      staticContext.promises.push(this.load)
    }
  }

  render() {
    return (...)
  }
}

// usage
<StaticRouter context={context}>
  <Route path='/thing' component={Thing} />
</StaticRouter>
```
That is obviously an incomplete example, but the point is that if you want something to exist on the `context` object, just go ahead and put it on there.

**Comment by cquillen2003** [comment] 2017-08-29 23:56
@pshrmn That makes sense.  However, I think there would be a benefit in adding a standard, default solution.  Especially if context is the only straightforward way of determining data dependencies on the server without a static route config.

Again, at the very least the docs should mention this OR some other way of server rendering while keeping the V4 philosophy of "Dynamic Routing".
