### ISSUE TITLE
[v6.alpha-3] Missing location prop on <Routes> breaks animated transitions.

### ISSUE THREAD

**Issue by abolo** [ReactTraining/react-router#7280] opened 2020-04-23 18:55 UTC
Hi guys! 
We're very excited about this new version of react-router! We've been doing some testing on a few existing projects runing previous versions of react-router and found a problem with animated transitions. 

In previous versions of react-router the **`location`** prop on the **`<Switch>`** component was a key element for creating animated route transitions like the one on the React Router documentation example: https://reacttraining.com/react-router/web/example/animated-transitions.

Now, with the new **`<Routes>`** component the **`location`** prop is gone, and all our transitions don't work as expected. 

This problem can be seen on the following link, it's the documentation example migrated to react-router 6:  [https://codesandbox.io/s/react-router-animated-transitions-2zovw](https://codesandbox.io/s/react-router-animated-transitions-2zovw)

Is there any workaround to fix this behaviour on this upcoming version?

Thanks!

**Comment by timdorr** [comment] 2020-04-23 22:28
Duplicate of #7117

**Closed by timdorr** 2020-04-23 22:28 UTC
