### ISSUE TITLE
Documentation website links are all broken

### ISSUE THREAD

**Issue by agriffis** [ReactTraining/react-router#7632] opened 2020-09-25 15:26 UTC
All the internal links on the document website seem to be broken. They all have an extra "react-router" segment that causes them to fail.

For example, go to https://reactrouter.com/web/api/Hooks which looks like the screenshot below. Click on any of the hooks listed (useHistory, useLocation, useParams, useRouteMatch) and you will land on https://reactrouter.com/ instead of the intended page

![image](https://user-images.githubusercontent.com/50637/94285533-c443c200-ff21-11ea-9b47-f50bcb9656aa.png)

**Comment by timdorr** [comment] 2020-09-25 15:30
Duplicate of #7484

**Closed by timdorr** 2020-09-25 15:30 UTC
