### ISSUE TITLE
[Website] Broken reactrouter.com or reacttraining.com/react-router

### ISSUE THREAD

**Issue by elartix** [ReactTraining/react-router#7770] opened 2021-02-17 12:17 UTC
### Version
Current website at https://reactrouter.com or https://reacttraining.com/react-router

### Steps to reproduce
Just open document site

### Expected Behavior
I'd love to open doc site without VPN

### Actual Behavior
Screen is blank:

![Снимок экрана 2021-02-17 в 14 01 02](https://user-images.githubusercontent.com/1899626/108202698-31066580-712a-11eb-8656-9be532c761e3.png)

### The Problem
I'm living in Ukraine and as a result I can't open document site without VPN

![Снимок экрана 2021-02-17 в 14 24 36](https://user-images.githubusercontent.com/1899626/108204964-20a3ba00-712d-11eb-8c23-5140f668d834.png)

**Comment by timdorr** [comment] 2021-02-17 15:07
This is due to Cloudflare being used on the site. Dupe of #7760

**Closed by timdorr** 2021-02-17 15:07 UTC
