### ISSUE TITLE
State of v6?

### ISSUE THREAD

**Issue by mariusmarais** [ReactTraining/react-router#7824] opened 2021-04-20 10:05 UTC
Apologies in advance for such an _impolite_ question, but is v6 still on track?

I'm starting a new project and from the dev branch docs, v6 looks perfect, but I am concerned that very little movement has happened on that branch in the last 4 months.

The v6 bug reports are to be expected, it's beta after all, but there doesn't seem to be any movement in closing them out, even for duplicates. (Mostly looking at splat matching issues, which brought me here.) I'm happy to be on the bleeding edge, as long as some progress is being made.

So, is there a roadmap for v6, or is it a "it's done when it's done" case? Is development on v6 still active?

I'm not really interested in using anything less than v6 -- I'd rather use another lib then.

**Comment by timdorr** [comment] 2021-04-20 14:24
Duplicate of #7613

**Closed by timdorr** 2021-04-20 14:24 UTC
