### ISSUE TITLE
[website]

### ISSUE THREAD

**Issue by Flandre-X** [ReactTraining/react-router#7650] opened 2020-10-09 12:19 UTC
## Expected Behavior

Clicking a link in the docs will send the user to the corresponding location in the docs.

![image](https://user-images.githubusercontent.com/38332081/95581992-93728b00-09ff-11eb-9f41-11c81cd69cd0.png)

## Actual Behavior

Clicking a link in the docs sends the user back to the homepage.

![image](https://user-images.githubusercontent.com/38332081/95581921-7047db80-09ff-11eb-9329-9d9120fcc4a3.png)

(route doesn't exist, so user is redirected to homepage)

**Note:** This only applies to links _within_ the docs, not nav links.

**Comment by timdorr** [comment] 2020-10-09 13:19
Duplicate of #7484

**Closed by timdorr** 2020-10-09 13:19 UTC
