### ISSUE TITLE
3.0.2 current route onLeave hook called twice when using replace in onEnter

### ISSUE THREAD

**Issue by VovanR** [ReactTraining/react-router#5434] opened 2017-08-15 12:54 UTC
## Version
3.0.2

## Test Case
https://jsfiddle.net/VovanR/wpex78o8/

## Steps to reproduce
Click **bar**
Click **foo**

## Expected Behavior
`"onLeave bar"` once
```
"onLeave bar"
"onEnter foo"
"onEnter baz"
```

## Actual Behavior
`"onLeave bar"` twice
```
"onLeave bar"
"onEnter foo"
"onLeave bar"
"onEnter baz"
```

**Comment by yuan252525** [comment] 2017-08-30 02:57
第三方第三方

**Comment by timdorr** [comment] 2017-08-30 03:46
Duplicate of ReactTraining/history#427

**Closed by timdorr** 2017-08-30 03:46 UTC
