### ISSUE TITLE
[v6] Nesting Router components

### ISSUE THREAD

**Issue by ealionel** [ReactTraining/react-router#7849] opened 2021-05-17 14:00 UTC
Hello,
Using v6 I wanted to nest a `MemoryRouter` inside a `BrowserRouter` in order to handle some in memory routes inside a page. Is there a reason why nesting Router contexts is not possible anymore in V6?
As this piece of code says https://github.com/ReactTraining/react-router/blob/dev/packages/react-router/index.tsx#L238

Thanks

**Comment by ryqndev** [comment] 2021-06-03 01:38
Just ran into this. Found this relevant issue: #7375

**Comment by timdorr** [comment] 2021-06-03 14:14
Duplicate of #7375

**Closed by timdorr** 2021-06-03 14:14 UTC
