### ISSUE TITLE
No imperative router API documentation.

### ISSUE THREAD

**Issue by btholt** [ReactTraining/react-router#4177] opened 2016-11-11 17:11 UTC
v4 Docs:  The router imperative API has no documentation. It also may bear mentioning to a user the bare bones of how context works since most new to intermediate React uses don't know it even exists or how to access it.

Is this something you'd like help with?

**Comment by timdorr** [comment] 2016-11-11 21:10
Dupe of #4134

**Closed by timdorr** 2016-11-11 21:10 UTC
