### ISSUE TITLE
react-router-dom v4.0.0-beta.7 installs react-router v4.0.0-beta.8

### ISSUE THREAD

**Issue by peter-mouland** [ReactTraining/react-router#4674] opened 2017-03-09 10:35 UTC
## Version
4.0.0-beta.8

## Test Case
https://github.com/peter-mouland/react-lego

## Steps to reproduce
install react-router-dom v4.0.0-beta-7

now with 4.0.0-beta.7; running `npm run test:func` fails, it worked previously.
but with 4.0.0-beta.8; running `npm run test:func` now works

I'm not sure if this is expected, but i fixed my version to beta-7 to prevent further breaking changes affecting my app without me explicitly updating the router.  I didn't use a shrinkwrap file which meant the sub-dependencies weren't fixed.

I'm not sure if you'd class this as a bug or not, but if anyone now tries to install beta.7, i won't work as it's incompatible with react-router v4.0.0-beat.8 (which it installs).

might be something to watch out for or be careful of if beta.9 comes out?

**Comment by timdorr** [comment] 2017-03-09 14:18
Dupe of #4656

**Closed by timdorr** 2017-03-09 14:18 UTC

**Comment by peter-mouland** [comment] 2017-03-09 17:42
I see that issue is marked as closed, so i'm not sure why it is still a problem?

I noticed this PR was makred as the fix for it https://github.com/ReactTraining/react-router/pull/4657/files

but the latest code introduces the `^` again, does this mean it'll be a problem again in the future?

https://github.com/ReactTraining/react-router/blob/v4/packages/react-router-dom/package.json#L45

**Comment by timdorr** [comment] 2017-03-09 17:49
We mainly have to wait for lerna/lerna#511, because the thing we need from Lerna only exists as a flag on the CLI right now and that's pretty easy to fat-finger. 

And, more confoundingly, #4668 will switch us back to independent mode, where I'm not sure it even manages inter-package versions at all. But we'll also have to wait for that to see how everything fits together. 

Regardless, it is beta software, so it's kind of expected to run into breakages like this. This should be a non-issue once we go final and nail everything down.

**Comment by pshrmn** [comment] 2017-03-09 17:56
Wait until v4.1 drops to merge `react-router-redux`? :stuck_out_tongue:

I actually think that independent mode might be beneficial so that changes to `react-router-dom` or `react-router-native` don't force a version bump in the other.

**Comment by timdorr** [comment] 2017-03-09 17:59
Babel is discussing the same thing leading up to their 7.0.0 release. We can watch what they do, since it's the same basic problem, just a couple of orders of magnitude more painful for them to get wrong.

**Comment by peter-mouland** [comment] 2017-03-09 18:10
cool, i'm onboard with the whole beta thing (I started testing v4 out in alpha and enjoyed where and how its changed). It's fine for me, just wanted to raise it as i didn't see a previous issue (obviously i missed the one pointed out!)
