### ISSUE TITLE
Stateless component rendering twice. Jest. Enzyme

### ISSUE THREAD

**Issue by csantos1113** [ReactTraining/react-router#6673] opened 2019-03-28 20:42 UTC
## Version

react-router@4.3.1

## Test Case
I wanted to test a simple stateless component that is returning `<Redirect>` when a condition is met.
See the code example:
https://codesandbox.io/s/18or04lkp7

* In the `pure-component.test.js` test the output is the expected.
* In the `stateless-component.test.js` the component is rendered twice and a Redirect warning appears: _"You tried to redirect to the same route you're currently on:"_

## Steps to reproduce
* Open the codesandbox "Tests" tab
* Execute the tests
* Open the codesandbox "Console" tab
* See the console output

## Expected Behavior
* Stateless component to be rendered once.

## Actual Behavior
* Stateless component is rendered twice and triggers a `Redirect` warning
![Screen Shot 2019-03-28 at 4 45 16 PM](https://user-images.githubusercontent.com/9648559/55191593-f7649400-5178-11e9-9bb8-1bea732dfc76.png)

**Comment by csantos1113** [comment] 2019-03-28 20:43
Here is the same example running with the latest react-router version (`5.0.0`)
https://codesandbox.io/s/woxn22omy8

And the result is even worst, because the tests do not run at all:
```
Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.

Invariant Violation: Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.
    at invariant (https://woxn22omy8.codesandbox.io/node_modules/fbjs/lib/invariant.js:42:15)
    at scheduleWorkImpl (https://woxn22omy8.codesandbox.io/node_modules/react-dom/cjs/react-dom.development.js:12125:13)
    at scheduleWork (https://woxn22omy8.codesandbox.io/node_modules/react-dom/cjs/react-dom.development.js:12082:12)
    at scheduleCapture (https://woxn22omy8.codesandbox.io/node_modules/react-dom/cjs/react-dom.development.js:11958:5)
    at dispatch (https://woxn22omy8.codesandbox.io/node_modules/react-dom/cjs/react-dom.development.js:11979:11)
```

**Comment by StringEpsilon** [comment] 2019-03-28 23:28
That's quite a nasty bug.

The problem is that React doesn't know whether or not it should re-render functional components. So it *always* re-renders them. 

In short:

1. ```<Router >``` renders 
2. ```Stateless()``` renders
3. ```Redirect()``` renders
4. Redirect() pushes onto History
5. ```<Router >``` calls setState because of the listener on the history.
6. Back to step 1.

Simply making Redirect a class component fixes the issue. I'll create a PR soon.

**Comment by timdorr** [comment] 2019-03-29 02:24
This was previously addressed in #5003 and fixed by #5162. I'm logging off for the evening right now, but that's roughly what's going on here.

[I'd argue `locationsAreEqual` is the problem here.](https://github.com/ReactTraining/history/blob/master/modules/LocationUtils.js#L57-L65) Should `key` be considered when comparing two locations?

**Closed** 2019-04-02 13:12 UTC

**Comment by gabrielsadaka** [comment] 2019-04-30 04:11
Any idea on when this may make it into a release? I am currently experiencing this exact issue.

**Comment by banyan** [comment] 2019-05-09 07:05
Please release new version! 🙏
