### ISSUE TITLE
When React-Router v6 will be released? 

### ISSUE THREAD

**Issue by RIP21** [ReactTraining/react-router#7816] opened 2021-04-06 15:30 UTC
Hi folks! I tried to ask the same question on Discord but never got a response. So decided to ask here.
Any plans to release version 6 anytime soon this year? 
I'm using beta for some time and so far never had issues (but I'm not using anything advanced to be honest)
But the fact that v6 barely getting traction in recent months is a bit scary :)

Thanks!

**Comment by MeiKatz** [comment] 2021-04-06 16:33
I think there are three reasons: 1st Ryan and Michael currently working on their commercial framework called Remix, 2nd RRv6 will support features from React that are not released yet, 3rd: blame it on CoViD-19 :D

**Comment by timdorr** [comment] 2021-04-06 17:26
Duplicate of #7613

**Closed by timdorr** 2021-04-06 17:26 UTC

**Comment by RIP21** [comment] 2021-04-06 17:45
Thanks a lot for the answer. I should've used search :) Sorry.
