### ISSUE TITLE
Path is incorrect escaped => activeClassName is not applied (<NavLink />)

### ISSUE THREAD

**Issue by MeiKatz** [ReactTraining/react-router#6253] opened 2018-07-13 11:45 UTC
Hello at all,

I am currently facing the problem that there is no `activeClassName` applied to any `<NavLink />` components even if the path (`to`) definitely matches the url. I tried to find the reason why and I found that the problem is the following line: [NavLink.js#L25](https://github.com/ReactTraining/react-router/blob/master/packages/react-router-dom/modules/NavLink.js#L25).

## Version
4.3.1

## Test Case
E.g. my path is `/studiengaenge/60/module` and is escaped to `\/studiengaenge\/60\/module` in `NavLink.js`. After that `matchPath` compiles this path to `/^\\\/studiengaenge\\\/60\\\/module\/?(?=\/|$)/i`. The problem is, that `<Route />` expects a pattern like `/^\/studiengaenge\/60\/module\/?(?=\/|$)/i` to be the current route and therefore the path is seen as not the current one. I think that the escaping should be removed. When I use the unescaped path as argument for `<Route />` everything works as expected.

## Expected Behavior
I expect that `activeClassName` is applied but it isn't. Pattern for `<Route />` should be `/^\/studiengaenge\/60\/module\/?(?=\/|$)/i`.

## Actual Behavior
Pattern for `<Route />` is  `/^\\\/studiengaenge\\\/60\\\/module\/?(?=\/|$)/i`.

**Comment by MeiKatz** [comment] 2018-07-13 11:56
I am also not sure why `<NavLink />` needs escaping at all. Shouldn't `<Route />` be responsible for this?

**Comment by pshrmn** [comment] 2018-07-13 14:53
@MeiKatz have you seen #6201?

**Comment by timdorr** [comment] 2018-07-13 14:55
Yes, this is a dupe of that issue.

**Closed by timdorr** 2018-07-13 14:55 UTC

**Comment by MeiKatz** [comment] 2018-07-13 15:47
@pshrmn Yes, I have seen this issue. But for me it seems that this issue was solved with changing `path.resolve("node_modules")` to `"node_modules"`. I tried this but it didn't work for me. So I opened this new issue.

**Comment by MeiKatz** [comment] 2018-07-13 18:57
@pshrmn I will keep it in mind. Next time I will do so.
