### ISSUE TITLE
Hot swapping routes

### ISSUE THREAD

**Issue by laurentvd** [ReactTraining/react-router#2182] opened 2015-10-07 11:11 UTC
Love your work on react-router! I'm implementing i18n routes using `1.0.0-rc1` and I'm running into the following. The relevant code:

	render() {
		const childRoutes = this.props.generateRoutes();

		return (<Router ref="router" routes={ childRoutes } history={ this.props.history }/>);
	}

The child routes are not updated, even though I'm positive the childRoutes object has changed. When I navigate to a new url, it doesn't match any routes. Is hot-swapping routes a scenario the router should support?

**Comment by mjackson** [comment] 2015-10-10 00:29
> Is hot-swapping routes a scenario the router should support?

I'd like to support it, yes. But it's going to be tricky to support. Here's why:

We need to be able to identify which routes are effectively the same as the ones you gave us previously. This is similar to the way React needs to know which virtual DOM elements you give it are effectively the same as the ones you gave it the last time it called `render`. In order to do this we need a way to uniquely identify a route across prop changes (i.e. `data-reactid` for route objects).

Currently, we consider route objects to be unique (i.e. === unique, you generate your route objects once). There are two places (that I can think of right now, maybe more) where this is important:

1. Registering route hooks
2. Computing changed routes

#### Registering route hooks

When registering [`routerWillLeave` hooks](https://github.com/rackt/react-router/blob/master/docs/API.md#routerwillleavenextlocation), we [assign ids to route objects](https://github.com/rackt/react-router/blob/e7c6f3d848e55dda11595447928e843d39bed0eb/modules/useRoutes.js#L89-L93) so we can keep those hooks in a map keyed by route id.

#### Computing changed routes

When we [compute which routes are changing in a transition](https://github.com/rackt/react-router/blob/e7c6f3d848e55dda11595447928e843d39bed0eb/modules/computeChangedRoutes.js#L30-L57) we rely on route object identity to determine if a route was active in the previous state, so we know whether or not we're transitioning away from that route.

If we can work around these issues, hot swapping of routes should be doable.

/cc @gaearon who knows a lot about hot reloading

**Comment by laurentvd** [comment] 2015-10-10 22:43
Thank you for your extensive response! And great to hear you'd like to support this. I think it can be really beneficial (and even necessary for i18n sites, like mine).

About identifying which routes are effectively the same; I agree this would be ideal, but I think just replacing the routes and manually triggering a `history.pushState` would suffice in many cases.

### Registering route hooks
This is probably going to be a tough one. We could allow the developer to assign a name (or ID) to a route which should match the replacing route's name. If it doesn't match, it's an 'entering' route.

### Computing changed routes
Not sure if I understand this correctly, but would't it make sense to always leave all routes that are being replaced and enter the relevant new routes?

Small disclaimer; I'm fairly new to react-router, so sorry if I misunderstand things!

**Comment by garborg** [comment] 2015-10-24 16:34
This worked in react@1.0.0-beta3, right? Just confirming that I'm hitting the same issue and not missing something else in the upgrade path. In beta3, when I grew the `routes` array prop passed to the following render method, the router registered new `apps/[...]` child routes, but it does not in rc3:
```js
    render() {
        const { history, routes } = this.props;
        return (
                    <Router history={history}>
                        <Route component={App}>
                            <Route path="apps" component={AppsOrApp}
                                               onEnter={requireAuth}
                                               childRoutes={routes} />
                        </Route>
                    </Router>
        );
    }
```

**Comment by taion** [comment] 2015-10-24 18:46
I recall that @acdlite hit something with referential equality breaking on routes - is that something supported by redux-router or something?

**Comment by garborg** [comment] 2015-10-24 19:40
I'm not sure -- I didn't see that and haven't used `redux-router`.

**Comment by taion** [comment] 2015-11-19 00:41
To add some color on https://github.com/rackt/react-router/issues/2182#issuecomment-150840413, I actually resolved the issue there by allowing users to optionally specify names on routes, which would be used in preference to referential equality for asserting that routes were "equal".

I'm curious, though - could i18n routes be generated with the existing `getChildRoutes` API?

**Comment by taion** [comment] 2015-11-20 20:04
https://github.com/rackt/react-router/pull/2581 will add a warning when you attempt to do this.

**Comment by ryanflorence** [comment] 2016-01-12 06:07
Could probably render a `<Router key={something}/>` and then change the key to trigger react to unmount it and set up a new one.

You'd only want that key to change when the routes change though, and definitely don't want it in production, but it could maybe kinda work?

**Comment by matthewgertner** [comment] 2016-01-12 18:50
I ran into a related issue using `react-router` with Redux. I would like some of my routes to require authentication, where the user's login status is kept in Redux's centralized data store. My router component looks something like:

```
const mapStateToProps = reduction => {
  return {
    loginStatus: reduction.getIn(['appState', 'auth', 'loginStatus'])
  };
};

export default connect(mapStateToProps)(class App extends Component {
  static propTypes = {
    dispatch: PropTypes.func,
    loginStatus: PropTypes.number
  }

  render() {
    const { loginStatus } = this.props;

    return (
      <Router history={history}>
        <Route path="/" component={Root}>
          <Route path="Login" component={Login} />
          <Route
              path="SomeAuthenticatedRoute"
              component={SomeComponent}
              onEnter={(nextState, replace) => requireLogin(nextState, replace, loginStatus)}
          />
          </Route>
        </Router>
      );
    }

    return false;
  }
});
```

Of course this doesn't work since the `Route` is bound to the `Router` in `componentWillMount` and never updated when `loginStatus` changes (so the closure is always bound to the same old value). This looks to me like a fundamental incompatibility between Redux and `react-router`.

What I don't understand is why you can't check the routes in `componentWillRender` by comparing each existing route to the new route with the same path. And if any of the attributes of the `Route` element have changed, the route would be updated. I guess this is very naive since I only took a quick look at the source code, but I'd be interested to understand why an approach like this wouldn't work.

**Comment by taion** [comment] 2016-01-12 19:18
What do we do if something doesn't end up matching?

You can always use `getChildRoutes` or `getComponent` as needed. But really in this case you could just close over `loginStatus` differently via an instance method on your app.

**Comment by matthewgertner** [comment] 2016-01-13 07:59
@taion If something doesn't match you just replace the route, right? I would think you would want the routes to always correspond to the current `Route` elements and that you could achieve that by diff-ing the elements in `componentWillRender` as I suggested. But I don't know much about the internals.

Not sure what you mean by "an instance method on your app". With Redux you really only have access to the app state in `mapStateToProps` without resorting to hacks. I can and will use a hacky solution for now, but it would be awesome if there were a way to make `react-router` play nicely with Redux.

**Comment by matthewgertner** [comment] 2016-01-13 08:32
I took another quick look at `Router.js`. I guess what I don't understand is what bad thing would happen if you essentially ran the code from `componentWillMount` in `componentWillRender` as well so the transition manager gets the updated routes. Even if nothing changes, I can't see what bad thing would have if the routes are recalculated on every render cycle. Doing some sort of diff would be more of an optimization.

**Comment by taion** [comment] 2016-01-13 15:20
It's like 3 pages up on this comment thread... https://github.com/rackt/react-router/issues/2182#issuecomment-147016657

**Comment by matthewgertner** [comment] 2016-01-13 17:11
@taion Got it, thanks. Wouldn't https://facebook.github.io/react/docs/reconciliation.html work well for this use case as well?

**Comment by taion** [comment] 2016-03-11 22:03
For better or for worse, we already implicitly support this via the dynamic `getChildRoutes` hook.

Also, we tear down all the old leave routes upon leaving a route anyway.

I don't think there's much of a good reason to only have that one backdoor into route hot swapping support, so we should just add proper support for this on `<Router>`, since we effectively have such support anyway.

**Comment by BerkeleyTrue** [comment] 2016-03-14 23:05
Ran into this today while trying to implementing vanilla hot module replacement and calling ReactDOM.render with new routes.

**Comment by ryanflorence** [comment] 2016-04-16 19:58
@taion let's do it.

**Comment by taion** [comment] 2016-04-16 20:01
Cool! We should think about how exactly this works. I guess we should re-run the match if the top-level routes object breaks referential equality. It'd be nice if there were a way to simultaneously navigate to a new location and change the routes, though.

**Comment by gaearon** [comment] 2016-04-18 17:13
FYI this is one of the biggest blockers (behind the new docs) to shipping [React Hot Loader 3](https://github.com/gaearon/react-hot-boilerplate/pull/61).

It solves many existing issues with hot reloading setups but with the way it works, I don’t see a way to avoid updates propagating through the router, and the router seems to hold onto the old versions of components. I’m trying to debug to see if there is a workaround.

**Comment by taion** [comment] 2016-04-18 17:16
The router holding onto components is also the biggest blocker for https://github.com/reactjs/react-router/issues/3190. I don't see how to get around this for async routes/components though. Maybe an externalized cache with hooks to invalidate the cache on a hot reload?

**Comment by gaearon** [comment] 2016-04-18 18:02
I found a really hacky workaround for people who want to try React Hot Loader 3 in their projects: https://github.com/gaearon/react-hot-boilerplate/pull/61#issuecomment-211504531. It only works due to reliance on implementation details of both projects but it’s better than nothing. Just posting here in case somebody’s blocked on it.

**Comment by taion** [comment] 2016-04-18 18:55
@gaearon 

To my embarrassment, I've never gotten around to setting up hot reloading, so I don't understand what that workaround does.

Is the idea just to call `React.createElement` on the components to tickle them into reloading somehow? Or into seeing things having been reloaded?

If so, this might be better placed as a router middleware per https://github.com/reactjs/react-router/issues/3316 that acts on the `components` prop passed into `<RouterContext>`. This prop is an array of all the resolved components (or name-keyed component objects in the case of named components) that should be fully resolved, and would work with async routes, &c.

**Comment by gaearon** [comment] 2016-04-18 19:00
>Is the idea just to call React.createElement on the components to tickle them into reloading somehow? Or into seeing things having been reloaded?

Yeah, this would not have worked with any previous solution, but today we happen to perform this side effect in [`createElement`](https://github.com/gaearon/react-hot-loader/blob/next/src/patch.dev.js#L63) because for a variety of reasons it turns out to be the best “window into React”. I know it looks super icky 😄 .

**Comment by taion** [comment] 2016-04-18 19:02
We call `createElement` on all the components later on in `<RouterContext>`, though. There's no `shouldComponentUpdate` or anything on `<Router>` preventing that update from flowing through.

**Comment by gaearon** [comment] 2016-04-18 19:06
Yes but I believe we cache `components` in the `state` so we `createElement()` the initial versions of them. They are created by the `transitionManager` that AFAIK only does this once in `componentWillMount`.

**Comment by gaearon** [comment] 2016-04-18 19:10
So basically the hook I need is to be able to get this to do this:

```js
// render normally
render(<Router><Route component={A}><Route component={B} /></Route></Router>, rootEl)

// All I care is that React.createElement(C) and React.createElement(D) are called
// I don't care that much whether they get rendered although it would be nice so this doesn't seem as icky
render(<Router><Route component={C}><Route component={D} /></Route></Router>, rootEl)
```

**Comment by taion** [comment] 2016-04-18 19:18
I don't understand why the caching of the components in `state` is relevant. Does the hot loader monkey patch "state" such that once a component gets dropped in there, tickling it with `React.createElement` won't have the desired effect?

**Comment by taion** [comment] 2016-04-18 19:20
Oh! Okay, I see what you're doing now. That makes sense, all right.

**Comment by glenjamin** [comment] 2016-04-18 19:36
> To my embarrassment, I've never gotten around to setting up hot reloading, so I don't understand what that workaround does.

You're seriously missing out! I recommend playing around with the example at https://github.com/glenjamin/devboard/ to get a feel for how much better the feedback cycle is.

********

I tried to have a look through the code to help out here, but I couldn't for the life of me find where React Router is copying the routes into `state`! Can anyone point me in the right direction here?

The discussion above talks about a way to uniquely identify routes, am I missing something obvious here - surely the `path` is by definition the unique identifier of a route in a router? Could that be used as the "key" to preserve state between re-defined routes?

**Comment by taion** [comment] 2016-04-18 19:41
React Router is not copying the _routes_ into `state`. It's copying the components into `state`. The components get resolved in https://github.com/reactjs/react-router/blob/v2.2.4/modules/createTransitionManager.js#L92-L102, and ultimately through the callback chain, they get added to the transition manager's "state", which gets passed to https://github.com/reactjs/react-router/blob/v2.2.4/modules/Router.js#L77.

I'd love to just put some sort of path to the matched routes, but this won't work with async routes – those routes and components aren't guaranteed to be available locally, so there's no way to synchronously resolve the routes and components from any serializable description of the match.

**Comment by taion** [comment] 2016-04-18 19:41
And that latter point is why #3190 is tagged "the future".

**Comment by glenjamin** [comment] 2016-04-18 20:05
> React Router is not copying the routes into state. It's copying the components into state.

Ah ok, I managed to follow this a bit better now:

Routes get passed to the transition manager: https://github.com/reactjs/react-router/blob/v2.2.4/modules/Router.js#L99

TransitionManager uses routes to match in a couple of places:
https://github.com/reactjs/react-router/blob/v2.2.4/modules/createTransitionManager.js#L57
https://github.com/reactjs/react-router/blob/v2.2.4/modules/createTransitionManager.js#L127

TransitionManager provides no way to change this cached route definition after it's initial creation.

One option would be to keep a reference to the transition manager, and provide it an `updateRoutes` method that replaces the routing table. As long as the routes weren't modified then this appears like it wouldn't cause a major problem. This call could be made in https://github.com/reactjs/react-router/blob/v2.2.4/modules/Router.js#L131


So the question then becomes: if the TransitionManager's routes table were to be swapped out, what would break?

I've only just started reading react-router internals, so I'm not very clear on the answer to that. From my investigation it looks like this would be most likely to affect the hooks system.

This line especially would have a problem: https://github.com/reactjs/react-router/blob/v2.2.4/modules/createTransitionManager.js#L113

Would it be feasible to have the hooks system use the path as a key? I'm not overly familiar with async routes - but I believe you'd have to have them loaded before you need to check their hooks - so the path would be available by that point.

**Comment by gaearon** [comment] 2016-04-18 20:08
@glenjamin Not sure if helps but this thread has some older context: https://github.com/reactjs/react-router/issues/2182#issuecomment-147016657. (Not that I have any idea about this tuff 😄 .)

**Comment by taion** [comment] 2016-04-18 20:09
@glenjamin That's what I meant in https://github.com/reactjs/react-router/issues/2182#issuecomment-210884363. The question is how to e.g. simultaneously reload routes and update the location; I think that use case might be relevant.

**Comment by glenjamin** [comment] 2016-04-18 20:20
@gaearon I **think** both use cases in https://github.com/reactjs/react-router/issues/2182#issuecomment-147016657 can be served by using the path property

@taion I'm not sure I'm following you there, but I think I agree that the route match should be re-run when routes are updated.

If the path + params are the same, I think the router should just render, rather than trying to second-guess whether the component is the same or not - react should handle that case ok.

**Comment by taion** [comment] 2016-04-18 20:21
It can't "just render" – it's not guaranteed to be able to determine the routes and params from the path synchronously.

**Comment by glenjamin** [comment] 2016-04-18 20:28
How is that different from the case where we'd be rendering normally? I'm not clear why it would need to be synchronous.

What I mean by "Just render" is to not try and check that `OldMatchedComponent === NewMatchedComponent` to short-circuit (which happens implicitly at the moment via routes).

**Comment by taion** [comment] 2016-04-18 20:42
If all you store in state is the `path`, then how do you know you can render? Does every part of the route tree have to do the async resolution? Do we have to do the async resolution every time we re-render the router, even if there was no state update? And what do we show during the async resolution? It's tricky when it's not synchronous.

**Comment by glenjamin** [comment] 2016-04-18 20:57
> If all you store in state is the path, then how do you know you can render?
> And what do we show during the async resolution?

What happens when you init from `location`, or you get a `popstate` event? I'd imagine you could treat a Routes update in the same way.


Have you had a chance to experiment with HMR workflows yet? I'll try and find some time to experiment with the more exotic react-router features so I know more about what I'm talking about.


Leaving the async stuff aside for the moment, here are some use cases I would want to work as a router user also using HMR:

1. Add a new route into <Routes>, apply HMR, click link to new route - it works
2. Add a new route into <Routes> that matches my current URL, apply HMR, page switches (eg. `/abc/def`before `/abc/:id`, this might be the tricky one)
3. Change the definition of the currently displayed component, apply HMR, page re-renders with latest code (this currently doesn't work due to the way RHLv3 proxies components and the way react router caches the original routes/components)

**Comment by taion** [comment] 2016-04-18 21:03
The issue isn't "with HMR" specifically. It's that we want to isolate all the async handling into `<Router>` (and `match` in some cases).

As such, the state in the router needs to be something that can be synchronously resolved into what should be rendered.

The current `path` does not satisfy this – in fact nothing less than the component classes themselves can satisfy this in the general case, because `getComponent` callbacks on routes can supply arbitrary components, including asynchronously-resolved in-memory ones.

**Comment by gaearon** [comment] 2016-04-27 14:30
Hmm. I have a dumb question.

>We need to be able to identify which routes are effectively the same as the ones you gave us previously. This is similar to the way React needs to know which virtual DOM elements you give it are effectively the same as the ones you gave it the last time it called render. In order to do this we need a way to uniquely identify a route across prop changes (i.e. data-reactid for route objects).

Why does this matter? I would be happy with `componentWillReceiveProps` in the router that completely tears down the transition manager (firing `onLeave` for the current route), and then boots it from the ground with the new routes. As long as the DOM doesn’t get unmounted, I don’t see issues with this.

If people have issues where this happens unexpectedly (e.g. they render `<Router>` inside a component that gets updated independently, and the routes get reset on every render), we can either tell them to extract `routes` from the `render()` method so that they are referentially identical, or put this behavior behind a special flag (e.g. `<Router replaceRoutes>`).

What am I missing?

**Comment by taion** [comment] 2016-04-27 17:22
@gaearon 

The issue if we lose referential equality is that we consider all the routes as having changed, and end up firing `onLeave` on the "old" routes and `onEnter` on the "new" ones.

Previously we thought this was so undesirable as to be a deal breaker.

However, I think we now don't think it's that big of a deal, in which case we don't need to do any teardown – we just need to update the routes in the transition manager.

**Comment by gaearon** [comment] 2016-05-02 12:15
FYI, `react-hot-loader@3.0.0-beta.1` “just works” with RR again because we changed proxies to be updated during module definition rather than in `createElement`. So this issue is not as important for us (aside from the annoying warning).

**Comment by taion** [comment] 2016-05-02 15:04
That's doable – we just need to fire the transition hooks for consistency.

**Comment by taion** [comment] 2016-05-05 15:49
@gaearon How does it work? We don't reload the routes in the transition manager, so if you e.g. add a new route, the router won't route to it.

**Comment by gaearon** [comment] 2016-05-09 21:51
>How does it work? We don't reload the routes in the transition manager, so if you e.g. add a new route, the router won't route to it.

Yeah, hot reloading of routes themselves won’t work, but this isn’t a big priority for me. As long as updating individual components works (and now it does) I’m content.

**Comment by taion** [comment] 2016-05-09 21:53
Okay, that makes sense then. Just wanted to make sure I wasn't missing something.

**Comment by aight8** [comment] 2016-06-06 10:56
Any news about this issue? It's totally priority for me too and a total coverage of dev tool support is not the most important thing I think.

**Comment by aight8** [comment] 2016-07-06 17:25
Any news about this issue? Where can I help?

**Comment by tomconroy** [comment] 2016-07-06 17:41
FWIW [this project](https://github.com/denvned/isomorphic-relay-boilerplate/blob/master/frontend/src/app.js#L15-L33) demonstrates a workaround, simply re-mount your app in `module.hot.accept`

**Comment by taion** [comment] 2016-07-06 17:46
If we split out `LocationProvider` per https://github.com/reactjs/react-router/issues/3611, this might just work straightforwardly.

**Comment by moljac024** [comment] 2016-07-12 10:59
@tomconroy wouldn't that destroy local state though?

**Comment by Swiftwork** [comment] 2016-07-13 14:57
Until this issue is resolved could we possibly reduce the number of warning messages to once per page request? That way subsequent hot reloads wont fill the console with warnings (which currently are displayed as errors).

![image](https://cloud.githubusercontent.com/assets/455178/16807870/6760e66a-491a-11e6-900f-dfab02a186a7.png)

**Comment by kachkaev** [comment] 2016-07-13 15:02
@Swiftwork how about trying to hide the warnings with a regex? You can use `filter` input field for this similarly to how this is done for  _unknown props_ in React 15.2: https://github.com/react-bootstrap/react-bootstrap/issues/1994#issuecomment-230367989

**Comment by satispunk** [comment] 2016-07-19 15:55
@tomconroy Thx! This works for me!

**Comment by lucasbento** [comment] 2016-08-17 19:26
Any updates/workarounds (except changing `console.error` directly to disable the warnings) to solve this?

**Comment by chibicode** [comment] 2016-08-20 23:21
I've changed `console.error` directly:

```js
// Keep this until this is fixed: https://github.com/reactjs/react-router/issues/2182
console.error = (() => {
  const error = console.error
  return function (exception) {
    (exception && typeof exception === 'string' && exception.match(/change <Router /))
    ? undefined
    : error.apply(console, arguments)
  }
})()
```

**Comment by ryanflorence** [comment] 2016-09-14 04:09
v4 has no routes, just components that work with HMR naturally.

**Closed by ryanflorence** 2016-09-14 04:09 UTC
Labels: enhancement, the future

**Comment by laurentvd** [comment] 2016-09-14 07:16
Thanks @ryanflorence ! Really like where v4 is going. Makes much more sense.

**Comment by benwiley4000** [comment] 2016-09-25 07:00
@gaearon [On May 9](https://github.com/ReactTraining/react-router/issues/2182#issuecomment-218001137) earlier in this thread you mentioned that React Hot Loader 3 now works with component updates in React Router. Not sure which version you referred to. Is this true for React Router version 2, or version 3? I'd prefer to adopt React Router 4 when it's at least in beta.

**Comment by vdh** [comment] 2016-09-27 00:08
For anyone like me still on v3 and looking for a workaround, I've managed to get moderate success by writing a custom `module.hot.accept` that mutates the existing `routes` object to swap in new components.

Example provided in a gist for brevity:
https://gist.github.com/vdh/c241560382d7b3c4aebf68aac66b9446

It's not pretty at all (object mutation 😢 ), but it can at least hot-reload new components. It will unfortunately not preserve component state (since `Root` is renewed each time), and will not be able to hot-reload any actual structural changes to the routes. It's only capable of swapping out old components for new ones. It also doesn't support the `<Route>` syntax, only the less-popular object syntax. Frankly I never liked the way the `<Route>` syntax worked at all in v3 to begin with, so I look forward to v4 turning Pinocchio into a real boy… 😜

**Comment by leebenson** [comment] 2016-10-03 11:29
@vdh, thanks for sharing the gist - unfortunately it breaks with Relay. Any known workarounds for Relay props?

**Comment by leebenson** [comment] 2016-10-03 13:43
actually @vdh, for 'regular' React components, I've managed to do away with any workarounds entirely using [this format](https://github.com/denvned/isomorphic-relay-router/issues/55).

Basically, re-loading 'routes' and re-rendering based on the original props does the trick. It also preserves component state.

Relay is still broken, though, as explained in the above link.

**Comment by hnordt** [comment] 2016-11-10 21:40
I love React Router, but I have created [my own solution](https://github.com/smalldots/smalldots/blob/master/src/experimental/Router.js).

Run this, and be happy:

```jsx
import React, { Component } from 'react'
import Router from 'smalldots/lib/experimental/Router'

const Debug = ({ value }) => <pre>{JSON.stringify(value, null, 2)}</pre>

const Link = ({ to, children }) => (
  <Router>
    {({ push }) => (
      <a href={to} onClick={event => {
        event.preventDefault()
        push(to)
      }}>
        {children}
      </a>
    )}
  </Router>
)

class App extends Component {
  state = this.getRandomRoutes()

  // each 10 seconds new routes will be generated
  componentDidMount() {
    this.interval = setInterval(() => this.setState(this.getRandomRoutes()), 10000)
  }

  componentWillUnmount() {
    clearInterval(this.interval)
  }

  getRandomRoutes() {
    return {
      route1: Math.ceil(Math.random() * 1000000),
      route2: Math.ceil(Math.random() * 1000000)
    }
  }

  render() {
    return (
      <div>
        <p>
          Route 1: <Link to={`/${this.state.route1}`}>/{this.state.route1}</Link>
          {' '}
          &middot;
          {' '}
          Route 2: <Link to={`/${this.state.route2}`}>/{this.state.route2}</Link>
        </p>
        <Router>
          {router => ({
            [`/${this.state.route1}`]: route => <Debug value={{ code: 200, router, route }} />,
            [`/${this.state.route2}`]: route => <Debug value={{ code: 200, router, route }} />,
            '/*notfound': route => <Debug value={{ code: 404, router, route }} />
          })}
        </Router>
      </div>
    )
  }
}

export default App
```
