### ISSUE TITLE
basename='/' badly handled

### ISSUE THREAD

**Issue by ZeHiro** [ReactTraining/react-router#4533] opened 2017-02-15 09:23 UTC
## Version
4.0.0 beta6

## Steps to reproduce
Use a BrowserRouter with basename='/' : `<BrowserRouter basename='/'>`
Declare routes like this : 
```jsx
<Route exact path='/' component={ rootComponent }>
    <Route path='aPath' component={ aPathComponent }>
</Route>
```
Declare this link`<Link to='aPath'/>`

## Expected Behavior
The generated anchor should be `<a href='/aPath'></a>`

## Actual Behavior
The generated anchor is `<a href='http:aPath'></a>`

**Comment by pshrmn** [comment] 2017-02-15 15:24
A few things:
1. React Router currently does not support relative paths. There is work being done on this (#4459), but it is not supported yet.
2. I ran a quick test, and it actually worked. That makes sense because `history` just does `path = basename + createPath(location)` which in this case is `"/aPath" = "/" + "aPath"`. A `basename` isn't actually supposed to have a trailing slash, so with a proper `basename`, this would fail.
```js
const node = document.createElement('div')
ReactDOM.render((
  <BrowserRouter basename='/'>
    <Route render={() => (
      <Link to='aPath'>Test</Link>
    )} />
  </BrowserRouter>
), node)
console.log(node.innerHTML) // <a data-reactroot="" href="/aPath">Test</a>
```
3. This JSX contains multiple errors. It isn't relevant to testing this, so mentioning this isn't really important, but if you actually tried to use this, it would fail.
```js
<Route exact path='/' component={ rootComponent }>
    <Route path='aPath' component={ aPathComponent }>
</Route>
```

I am not sure where the `http` protocol that shows up in your generated link is coming from. You will need to provide a more fleshed out example that can be reproduced if you think that this is actually a bug, but for now I am going to close this.

**Closed by pshrmn** 2017-02-15 15:24 UTC
