### ISSUE TITLE
Why is LOCATION_CHANGE action too lazy when I use go back or forward button in browser

### ISSUE THREAD

**Issue by w4-geonhokim** [ReactTraining/react-router#5804] opened 2017-12-20 06:49 UTC
My version of
react-router: 5.0.6
react-router-redux: 5.0.0-alpha.6

I have code to move from a page to the other page with onClick=history.push() event in tr element. When I click the tr element, then it works fine. LOCATION_CHANGE is called fast enough.

However, if I use history back or forward button in browser, LOCATION_CHANGE action is even slower than rendering.

Below is captured image in my console.

When I just use onClick event in tr element:
<img width="400" alt="2017-12-20 3 54 39" src="https://user-images.githubusercontent.com/31527399/34194867-34c71f0e-e59e-11e7-9e22-e8315d81f224.png">

When I use go back and go forward button in browser:
<img width="398" alt="2017-12-20 3 55 00" src="https://user-images.githubusercontent.com/31527399/34194877-3e9393dc-e59e-11e7-90c6-73e3dd4f0178.png">
That 'null' is match.

I'm wondering the reason. Thank you.

**Comment by timdorr** [comment] 2017-12-20 15:13
Duplicate of #5072

**Closed by timdorr** 2017-12-20 15:13 UTC
