### ISSUE TITLE
prop-types warning 

### ISSUE THREAD

**Issue by 39Er** [ReactTraining/react-router#5161] opened 2017-05-23 12:32 UTC
In my project,there are two warnings about prop-types,I'm not sure whether they are related to react-router:
1.  Warning: getDefaultProps is only used on classic React.createClass definitions. Use a static property named `defaultProps` instead.

2.  Warning: Failed prop type: Calling PropTypes validators directly is not supported by the `prop-types` package. Use PropTypes.checkPropTypes() to call them.

**Comment by timdorr** [comment] 2017-05-23 17:40
Without stack traces, we have no way of knowing. 

But the first one is definitely not caused by the router, as we don't use that API. The second sounds like you need to upgrade your version of prop-types, as that was an issue fixed in a more recent release of that library.

**Closed by timdorr** 2017-05-23 17:40 UTC

**Comment by 39Er** [comment] 2017-05-24 01:06
ok,thanks for your advice,I'll try it!

**Comment by 39Er** [comment] 2017-06-02 09:58
Still got two warnings about react-router:

```
react.js:3287 Warning: Failed prop type: Calling PropTypes validators directly is not supported by the `prop-types` package. Use PropTypes.checkPropTypes() to call them. Read more at http://fb.me/use-check-prop-types
    in Route
Warning: Failed context type: Calling PropTypes validators directly is not supported by the `prop-types` package. Use PropTypes.checkPropTypes() to call them. Read more at http://fb.me/use-check-prop-types
    in Router (created by BrowserRouter)
    in BrowserRouter

```

How to resolve those warnings ?

**Comment by SevenWhite** [comment] 2017-06-11 09:07
I have this problem too.

![_027](https://user-images.githubusercontent.com/12198965/27009739-7310de5e-4e9e-11e7-9999-e7257d11526b.png)

**Comment by golddranks** [comment] 2017-06-15 13:31
Me too.
![2017-06-15 22 29 16](https://user-images.githubusercontent.com/2675542/27183624-3d28cb6a-521a-11e7-83a3-5a29d7ef3fcf.png)

These are my deps and devDeps:

```
  "dependencies": {
    "prop-types": "^15.5.10",
    "react": "^15.6.1",
    "react-dom": "^15.6.1",
    "react-redux": "^5.0.5",
    "react-router-dom": "^4.1.1",
    "redux": "^3.6.0"
  },
  "devDependencies": {
    "@types/react": "^15.0.28",
    "@types/react-dom": "^15.5.0",
    "@types/react-redux": "^4.4.43",
    "@types/react-router-dom": "^4.0.4",
    "awesome-typescript-loader": "^3.1.3",
    "babel-jest": "^20.0.3",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-react": "^6.24.1",
    "gulp": "^3.9.1",
    "gulp-webserver": "^0.9.1",
    "jest": "^20.0.4",
    "react-test-renderer": "^15.6.1",
    "redux-devtools": "^3.4.0",
    "source-map-loader": "^0.2.1",
    "typescript": "^2.4.0"
  }
```

**Comment by golddranks** [comment] 2017-06-29 06:22
For people finding this through Google: linking with @PeteX's freshly built version of this library from the thread linked below instead of using the one in NPM fixed the issue for me. 

https://github.com/ReactTraining/react-router/issues/5161

I think this is going to be solved when the next version of react-router is released.
