### ISSUE TITLE
[v5] Calling PropTypes validators directly is not supported

### ISSUE THREAD

**Issue by ericvilleneuve** [ReactTraining/react-router#5302] opened 2017-06-30 19:33 UTC
## Version
react-router-redux 5.0.0-alpha.6
I'm getting the error `Calling PropTypes validators directly is not supported` when using `5.0.0-alpha.6`.

Am I correct in assuming that it simply needs a rebuild and publish to ensure `prop-types` is updated with `15.5.10`, which fixes [this issue](https://github.com/react-bootstrap/react-bootstrap/issues/2610)?

Here is my stacktrace:
![react-router-redux](https://user-images.githubusercontent.com/6557209/27751254-678eda6c-5da9-11e7-8f71-a67d59b755ff.PNG)

Thanks!

**Comment by timdorr** [comment] 2017-06-30 20:17
Yep. Dupe of #5173

**Closed by timdorr** 2017-06-30 20:17 UTC
