### ISSUE TITLE
Re-adding support for exactly matching NavLinks in v4

### ISSUE THREAD

**Issue by swernerx** [ReactTraining/react-router#4504] opened 2017-02-09 20:08 UTC
We have a `NavLink` setup where we have the home link + child pages configured:

```html
<ul>
  <li><NavLink to="/" activeClassName={Styles.activeLink}>Home</NavLink></li>
  <li><NavLink to="/about" activeClassName={Styles.activeLink}>About</NavLink></li>
  ...
</ul>
```

Unfortunately this does not work as hoped for right now. "Home" is always active even if some other child page is active, too. I'd like to get the functionality back to have strict matching `NavLinks`. Otherwise typical navigation bars are kind of problematic with this component.

**Comment by timdorr** [comment] 2017-02-09 20:28
Dupe of #4411 (which is fixed)

**Closed by timdorr** 2017-02-09 20:28 UTC
