### ISSUE TITLE
Quick Start page on documentation broken

### ISSUE THREAD

**Issue by rodryquintero** [ReactTraining/react-router#3894] opened 2016-09-17 16:50 UTC
## Version
4.0.0

## Test Case
No scroll bars on the right.
![image](https://cloud.githubusercontent.com/assets/1271370/18609669/08a625d6-7ccd-11e6-8994-c03a20bf75f8.png)

## Steps to reproduce
Just click on the Quick Start link

## Expected Behavior
You should be able to scroll down to see the entire page.

## Actual Behavior
Only displays the page on the viewport dimensions and you cannot scroll down to see the rest of the page's content.

**Comment by StokeMasterJack** [comment] 2016-09-17 17:14
I'm getting the same thing.

**Comment by timdorr** [comment] 2016-09-17 19:14
Dupe of #3859. Fixed in e12f607.

**Closed by timdorr** 2016-09-17 19:14 UTC
