### ISSUE TITLE
NavLink with get params in the url is not marked as active

### ISSUE THREAD

**Issue by ivanhoe011** [ReactTraining/react-router#6268] opened 2018-07-27 13:14 UTC
## Version
react-router-dom 4.3.1

## Test Case
https://codesandbox.io/s/zw01k9v18m

## Steps to reproduce
Click on the 2nd link in the codesandbox preview or go to: https://zw01k9v18m.codesandbox.io/?foo=123 in the preview. 

## Expected Behavior
When url is https://zw01k9v18m.codesandbox.io/?foo=123
Both NavLink elements should have active class set, as both match the url (if search part is ignored they're the same)

## Actual Behavior
When url is https://zw01k9v18m.codesandbox.io/?foo=123
First link is correctly marked as active:
`<NavLink to="/">Active</NavLink>`

The 2nd, which matches the url exactly, is NOT marked as active:
`<NavLink to="/?foo=123">Exact url, but not active</NavLink>`

I've tried a few combinations and the problems are the search params in the to="" prop. IMO, if router is ignoring the search query in routing, than it's to be expected to ignore it when matching the active links to, right?

I know it's possible to work around this using isActive prop, but it's a hassle, plus this looks like a bug to me, not a feature.

**Comment by ivanhoe011** [comment] 2018-07-27 14:07
After looking through the code a bit, it seems that it could be fixed very easy by removing the search part from the "to" prop in https://github.com/ReactTraining/react-router/blob/master/packages/react-router-dom/modules/NavLink.js#L22

Replacing:
`const path = typeof to === "object" ? to.pathname : to;`
with: 
`const path = typeof to === "object" ? to.pathname : to.replace(/\?.+$/, "");`

If you're OK with this change, I'll be happy to create a PR?

**Comment by timdorr** [comment] 2018-07-27 15:18
I've been thumbs downed to all hell on this before, but I'll give you the bad news anyways... 😬 

This is a dupe of #5379. Since we don't do query string parsing anymore, we consider the full URL, including the query string, when matching for "active-ness" of a NavLink. You can wrap NavLink with an `isActive` custom function to make this workable if it fits your use case:

```js
export const PathNavLink = props => (
  <NavLink isActive={(_, { pathname }) => pathname == props.to} {...props} />
)
```
I understand that's a little work on your end. This is a philosophical choice made early on in Router 4.0's development: That we don't want to solve for every possible use case, but instead provide a base amount of functionality that lends itself towards easy composition to achieve greater functionality. We found in prior versions that trying to solve every edge case was a losing game, so we dealt with other people upset at API or implementation choices that didn't serve their needs. 

Anyways, that's the long and short of it. Hope I don't get too many thumbs downs and angry tweets this time 😄

**Closed by timdorr** 2018-07-27 15:18 UTC

**Comment by ivanhoe011** [comment] 2018-07-27 16:11
I fully understand and respect this design choice, but I think this is a bit different issue as basically as it is now, the NavLink is broken if the "to" prop is given an url with a query string. It can never be matched as active, as the matching code is not using search, but the "to" prop is not sanitized to remove the search and hash parts before the check. 

Why not removing the search query from both parts that are compared, to make the matching code really ignore the search params and work regardless of it?
