### ISSUE TITLE
Have Prompt's when also take a function with nextLocation

### ISSUE THREAD

**Issue by fingermark** [ReactTraining/react-router#5009] opened 2017-04-21 00:52 UTC
## Version
4.0.0

Can we have `Prompt's` `when` also be a function that takes in the next location, like `message`.  I have a use case where I want to prompt block when a user leaves the root of a certain path.  For example, I'd allow navigating from `/foo/1` to `/foo/2` or `/foo`, but not `/bar` or `/bar/1`.  

If I take the topics example and put the following at the Topics root, it will prompt on all transitions going forward, when I just want it to prompt whenever it leaves Topics.  I think this would be easiest if when supported a function, but there are likely other solutions.

```
    <Prompt
      when={true}
      message={'Exit?'}
    />
```

**Comment by timdorr** [comment] 2017-04-21 02:37
Dupe of #4743

**Closed by timdorr** 2017-04-21 02:37 UTC

**Comment by fingermark** [comment] 2017-04-21 03:25
Hey @timdorr.  Thanks for following up on this issue so quickly.  I See #4743 is closed.  Is this something that's awaiting a PR?  Or is something @ryanflorence wasn't interested in adding?
