### ISSUE TITLE
[Feature request] Switch support for React fragments?

### ISSUE THREAD

**Issue by FredyC** [ReactTraining/react-router#5917] opened 2018-01-30 16:23 UTC
[React fragments](https://reactjs.org/docs/fragments.html) are quite a new feature and most probably not used much just yet. In my opinion it's good fit in routing where you want to avoid rendering unnecessary elements (divs).

I have a semi static routing for the app, but instead of a single file with all routes, I have them split among many other files - one per app feature.

```jsx
export const LoginRoutes = () => (
  <React.Fragment>
    <PasswordLoginRoute />
    <SocialLoginRoute />
  </React.Fragment>
)

export const App = () => (
  <Switch>
    <LoginRoutes />
    <DashboardRoutes />
    <NotFoundRoute />
  </Switch>
)
```
The `Switch` here is always picking the last route for obvious reasons. Other way around would be probably to return array and manually merge these into a flat structure, but it's not that pretty for sure.

I am curious if this something you would like to support? It's fairly easy to recognize fragment node (it has a `type` attribute equal to `React.Fragment`. That leaves only trouble with flattening children of every fragment node.

Or do you have any tips & tricks how to solve this differently while keeping nice declarative approach?

**Comment by brianespinosa** [comment] 2018-01-30 16:29
Duplicate of #5785

**Closed** 2018-01-30 16:30 UTC

**Comment by FredyC** [comment] 2018-01-30 16:35
Yea, that was dumb of me. I appologize :) I am not sure why I though that I am bringing something _new_ on the table and don't need to use search.

**Comment by timdorr** [comment] 2018-01-30 16:38
Believe me, this is the least dumb thing I've seen on GitHub today.
