### ISSUE TITLE
TypeError: Cannot read property 'propTypes' of undefined

### ISSUE THREAD

**Issue by lunika** [ReactTraining/react-router#6638] opened 2019-03-18 09:13 UTC
## Version

```
react-router: 4.4.0
react-router-dom: 4.4.0
```

## Expected Behavior

After upgrading from version `4.3.1` to `4.4.0` I expect my tests to run without error.

## Actual Behavior

Application tests are failing with this error: 

```
    TypeError: Cannot read property 'propTypes' of undefined

      1 | import * as React from 'react';
      2 | 
    > 3 | const ReactRouter: any = jest.genMockFromModule('react-router-dom');
        |                        ^
      4 | 
      5 | // Stub withRouter to just return the wrapped component
      6 | // This allows us to run shallow() and still get the Component itself directly.

      at Object.<anonymous> (node_modules/react-router-dom/cjs/react-router-dom.js:280:30)
      at Object.<anonymous> (node_modules/react-router-dom/index.js:6:20)
      at Object.<anonymous> (__mocks__/react-router.tsx:3:24)
      at Object.<anonymous> (components/VideoPlayer/VideoPlayer.tsx:44:20)
      at Object.<anonymous> (components/VideoPlayerConnected/VideoPlayerConnected.tsx:18:20)
      at Object.<anonymous> (components/VideoPlayerConnected/VideoPlayerConnected.spec.tsx:9:29)
```

The project where I have this issue is opensource, you can see the PR where the error appears here: https://github.com/openfun/marsha/pull/259

I try to downgrade Jest version and I still have the same error so I think it is more a `react-router` regression than a jest one (both packages are upgraded in this PR).

Thank you for your help.

**Comment by timdorr** [comment] 2019-03-18 12:00
Have you tried clearing your build cache? We definitely export Route with a propTypes property and you have all the right versions of things. That's all I could think of.

**Comment by Xazzzi** [comment] 2019-03-18 13:30
I have the same problem. Will try reverting back to 4.3.1 for now.

**Comment by lunika** [comment] 2019-03-18 13:36
> Have you tried clearing your build cache? We definitely export Route with a propTypes property and you have all the right versions of things. That's all I could think of.

On the CI I have no cache, it's a fresh install and I have the same issue.

**Comment by timdorr** [comment] 2019-03-18 13:48
Dupe of #6639

**Closed by timdorr** 2019-03-18 13:48 UTC

**Comment by fff2139678** [comment] 2019-03-22 08:54
Version：
react-router: 5.0.0
react-router-dom: 5.0.0

Application tests are failing with this error:

react-router-dom.js:278 Uncaught TypeError: Cannot read property 'propTypes' of undefined
    at eval (react-router-dom.js:278)
    at Module../node_modules/_react-router-dom@5.0.0@react-router-dom/esm/react-router-dom.js (app.js:4830)

I have the same problem.

**Comment by craigdallimore** [comment] 2019-04-15 04:07
If it helps anyone - we temporarily had this issue in Jest with a manually mocked `react-router`, like so

```js
// Produces the same bad effect
jest.mock('react-router', ...)
```
