### ISSUE TITLE
componentWillUnmount after onEnter new route

### ISSUE THREAD

**Issue by marlonmleite** [ReactTraining/react-router#5779] opened 2017-12-10 00:31 UTC
When you visit routeA and click on routeB, the componentWillUnmount of routeA is triggered after onEnter routeB.

This is correct?

I am trying various problems with state undefined in my components because of this behavior.

**Comment by timdorr** [comment] 2017-12-11 01:03
Duplicate of #5325.

**Closed by timdorr** 2017-12-11 01:03 UTC
