### ISSUE TITLE
Route changes don't re-render Links

### ISSUE THREAD

**Issue by spicydonuts** [ReactTraining/react-router#3935] opened 2016-09-23 15:55 UTC
## Version
4.0.0-alpha.3

## Steps to reproduce
Put Link components in a location that persists across pages (like a nav bar).  Use Matches to change the content area based on the current route.

## Expected Behavior
Links should re-render (or at least consider re-rendering in a `shouldComponentUpdate`) when the location changes.

## Actual Behavior
The 'active' statuses of the Link components do not change unless they are forced to re-render.

**Comment by spicydonuts** [comment] 2016-09-23 16:20
This is related to being within Redux (or some other pattern that implements `shouldComponentUpdate`).  The basic routing example in the docs is relying on having every component re-render.  Here's that basic example extended slightly to show the issue: https://gist.github.com/spicydonuts/74e084f03a028aaadf5893e2a32b741b

So, here's a crazy sort of related idea and I can already guess the answer, just want to make sure it's been considered.. 🙈

Instead of wrapping the app in a Router and it using its own routing and location context, the router could be a Redux plugin similar to redux-form & Apollo.  Apollo's actually a great example because you can use it with or without Redux.  If you use it without Redux it just wires up some hidden Redux defaults behind the scenes.  Various router components would no longer need to [do their own subscription management](https://github.com/ReactTraining/react-router/blob/v4/modules/Match.js#L21), and non-React tools would be able to easily access location info via Redux.

**Comment by timdorr** [comment] 2016-09-23 18:30
Interestingly, this just came up on Twitter: https://twitter.com/ryanflorence/status/779320581678174208

Honestly, it's not really something we can handle. If a wrapping component wants to short circuit rendering too high up in the tree without informing its children, there's nothing we can do to stop that on our end. This is more of an issue with React than the Router.

Incidentally, with the changes coming in react-redux, I'm thinking we can get rid of the sCU usage and clear up this mess. `connect()` used to have to try and outsmart the user, but now that we're moving to `reselect`, it shouldn't need to be that much of a smart ass component anymore 😄

**Closed by timdorr** 2016-09-23 18:30 UTC

**Comment by spicydonuts** [comment] 2016-09-23 22:07
Exactly the clarification I was looking for, thanks!

**Comment by vanthiyathevan** [comment] 2016-09-26 18:13
I've managed to get a workaround for this. All you need to do is map the location context to props before applying connect. If you are using [recompose](https://github.com/acdlite/recompose) then its easy. This will return `true` for `sCU` of `connect`
see [updated gist](https://gist.github.com/vanthiyathevan/b9911137199431485f3c45cf7811cc93)

**Comment by spicydonuts** [comment] 2016-09-26 21:37
That's much better than wrapping the parent in a `<Match pattern="/" />`, thanks for the example!

**Comment by spicydonuts** [comment] 2016-09-26 22:17
Ooops.. nevermind: https://gist.github.com/spicydonuts/44e6f60c60b231e248dfb290d576d89e

It still breaks when there are multiple levels (I wrapped `Nav` in one more `connect`)

**Comment by pshrmn** [comment] 2016-09-26 22:55
If you need the connected component to update, why not make the connect impure?

```javascript
const Nav = connect(null, null, null, {pure: false})(
  () => (
    <ul>
      <li><Link to="/" activeClassName="active">Home</Link></li>
      <li><Link to="/about" activeClassName="active">About</Link></li>
      <li><Link to="/topics" activeClassName="active">Topics</Link></li>
    </ul>
  )
);
```
You could include a wrapper if you're using it often.

```javascript
function AlwaysUpdateConnect(mapState = null, mapDispatch = null, mergeProps = null, options = {}) {
  return connect(
    mapState,
    mapDispatch,
    mergeProps,
    Object.assign(options, {
      pure: false
    })
  );
}

const Nav = AlwaysUpdateConnect()(
  () => (
    <ul>
      <li><Link to="/" activeClassName="active">Home</Link></li>
      <li><Link to="/about" activeClassName="active">About</Link></li>
      <li><Link to="/topics" activeClassName="active">Topics</Link></li>
    </ul>
  )
);
```

**Comment by spicydonuts** [comment] 2016-09-26 23:16
Because parents shouldn't need to know that much about their children.  There are links scattered throughout the app, at all levels.  Using React Router with Redux shouldn't require turning off all of pure-render everywhere.  I've also seen discussions about using pure-render as the default sCU for function-components, which would present the same problem.

As @timdorr mentioned above, this seems like a more fundamental issue with React's context feature than anything else.. (and it seems like a good time to point out again that it'd be really really nice to use React Router _via_ Redux for those that want to opt into it.. something like "if you put `<Router>` inside `<Provider>` and specify some option to put `location` into the store instead of onto context.. 🙂 maybe haha)

**Comment by tyrsius** [comment] 2016-09-26 23:29
@timdorr I don't think you should have closed this. You may not have a solution, but that doesn't make the problem non-existant. People are going to run into this. I am upgrading from React-Router v2 to v4, and I had `<Links>` in my NavBar that broke for this exact reason. You are saying that can't be fixed, but that's a pretty good reason to leave this issue open. If a workaround comes out, great. If not, then people should know that a *major, common use case* that worked in V2 is unfixably broken in V4, and maybe they shouldn't waste their time trying to upgrade.

**Comment by timdorr** [comment] 2016-09-27 00:34
@tyrsius You'll run into this with react-redux with many libraries. react-bootstrap has fought this issue a lot as well. It's not caused by anything the router is doing, nor can we do anything to fix it. It's something I'm hoping to get fixed on react-redux in 5.0 soon.

**Comment by tyrsius** [comment] 2016-09-27 00:37
Yea, but it's a problem that existed in v2, and it's not mentioned anywhere
in the docs. It's a big breaking change, and open issues are where people
will look after reading the docs.

**Comment by timdorr** [comment] 2016-09-27 00:39
I'm not sure what you're asking me to do. It's a quirk (not necessarily a bug) in how React handles context with sCU implemented in a parent component. There's nothing we can do about it.

**Comment by tyrsius** [comment] 2016-09-27 17:53
You have a pretty decent workaround in development [here](https://github.com/reactjs/react-router-redux/pull/460). A road sign about where to go next was all I was after, and that workaround is good enough. I've actually got this working now, using that and a `connect`ed `Link`

**Comment by spicydonuts** [comment] 2016-09-27 20:28
> There's nothing we can do about it.
It's certainly a valid position that this is a React issue and not the router's concern, but it's completely _possible_ to work around React and fix it.  `Match` already works around it by subscribing to route updates.  It's not ideal.. hopefully React manages to find a solution, but having `Link` subscribe the way `Match` does seems.  Besides, if React fixes context+sCU somehow it would remove `Match`'s need for custom subscriptions as well.. The current approach just seems weird because half has a workaround and half doesn't.

**Comment by ChazUK** [comment] 2016-11-14 17:06
Am I correct in thinking there isn't going to be a fix for this?

I just moved my menu open prop to the state using Redux and have noticed this issue, as now none of the links are updating with their activeClassName.

**Comment by timdorr** [comment] 2016-11-14 17:16
Link already has this fixed (so my previous comments are now outdated), it's just not released yet. It uses the same subscription mechanism as Match.

**Comment by ChazUK** [comment] 2016-11-14 17:33
@timdorr Thanks for the quick reply! Is there an ETA on when this new release will be available, or is there a beta branch I can pull from?

**Comment by timdorr** [comment] 2016-11-14 17:41
Yep, just grab from the v4 branch.

**Comment by etiennejcharles** [comment] 2017-04-09 03:09
This post actually helped me work around the issue: 

https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/guides/blocked-updates.md#the-solution

If anyone comes across this post - I suggest you read this, you need to pass down the location object, in order to force an update when your component is connected to redux.

**Comment by benjaminhoffman** [comment] 2017-09-22 15:47
For those reading this thread and are using Redux, this solution worked for me!  I wrapped my `connect` in `withRouter`

https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/guides/redux.md#blocked-updates
