### ISSUE TITLE
All in-docs section links are broken

### ISSUE THREAD

**Issue by meetmangukiya** [ReactTraining/react-router#7600] opened 2020-09-05 14:24 UTC
Each of these links seem to be prefixed with `react-router`. Same is the case for all - core, web and native documentation. Each link(inside docs, not the sidebar, the sidebar links are fine) is prefixed with `react-router`.

## Test Case

Example - https://reactrouter.com/react-router/web/guides/quick-start/2nd-example-nested-routing while it should be https://reactrouter.com/web/guides/quick-start/2nd-example-nested-routing. 

Referenced links are also broken the same way. Example: check reference to `history` in `useHistory` hooks docs.

## Expected Behavior

The links should work, and not fallback to default route - the homepage.

**Comment by timdorr** [comment] 2020-09-06 00:57
Duplicate of #7484

**Closed by timdorr** 2020-09-06 00:57 UTC
