### ISSUE TITLE
Scroll management

### ISSUE THREAD

**Issue by nhagen** [ReactTraining/react-router#3950] opened 2016-09-26 17:05 UTC
Loving the v4 API currently! Wanted to start a thread on this so the community can stay updated. From the FAQ:

> What about scrolling?
> 
> We have some code close to being published that will manage the scroll positions of window and individual elements.

Whose working on this, and whats the ETA for this? Will it still be provided by the `react-router-scroll` library?

**Comment by mjackson** [comment] 2016-09-27 18:05
I have a POC on my machine, but it requires #3956 to be fixed before it works.

**Comment by ryanflorence** [comment] 2016-10-26 02:12
@mjackson it is fixed! just not released yet.

**Comment by IljaDaderko** [comment] 2016-11-09 16:23
@ryanflorence Any updates on this? Scroll management would be good to have in a router :)

**Comment by ericvrp** [comment] 2016-12-07 13:47
ScrollManagement on v4 still open or fixed? I to would my page to show the same after router.goBack()

**Comment by cjke** [comment] 2016-12-19 02:05
As a temporary solution this SO Question + Accepted answer have worked for me: http://stackoverflow.com/questions/40217585/in-react-router-v4-how-does-one-link-to-a-fragment-identifier

**Comment by PascalPixel** [comment] 2017-01-24 05:31
Update on status please?

**Comment by timdorr** [comment] 2017-02-01 21:09
@mjackson Are we deferring to the browsers on this or putting something together (or updating your POC)?

**Comment by mjackson** [comment] 2017-02-02 00:58
I'll see if I can push an updated POC soon.

**Comment by steida** [comment] 2017-02-03 05:53
RR4 ScrollManagement is like Gulp 4. Maybe this year.

**Comment by steida** [comment] 2017-02-06 02:23
Party pooper here. In case of next POC will take next several months, maybe this could help meanwhile: https://github.com/4Catalyzer/found-scroll

**Comment by mjackson** [comment] 2017-02-06 04:33
😂 @steida, you're such a helpful ray of sunshine. thank you!

**Comment by wmdmark** [comment] 2017-02-12 07:40
Is the really no way to control scroll with RR4? I was using the `history.listen` API directly in RR3 to scroll to top when the route changed but that doesn't appear to work any more in 4. Maybe I'm just doing something wrong?

**Comment by mjackson** [comment] 2017-02-13 04:40
OK, I'm going to try and find an elegant solution to this problem this week for (at least the DOM bindings in) v4. Up to this point I've focused all my attention on making sure we had a good core, and now that we're shipping v4 betas every few days I think we're there.

If you're interested in trying to scratch your own itch and solve this problem for your app, but you've been hesitant because v4 was too unstable, you should feel free to give it a shot now too.

For folks who are interested, we've got quite a backstory that you can follow right here in this repo. Here are a few links that should help you get a feel for research that has already been done in previous versions:

- #129 added the `<Route preserveScrollPosition>` API
- #252 disabled automatic scrolling when clicking on `<Link>`s
- #326 replaced `<Route preserveScrollPosition>` with the `<Route scrollStrategy>` API
- #707 described a bug with the approach we were taking

And for everyone who thinks "oh my gosh I can't believe they don't have an answer for this yet" I refer you to https://github.com/ReactTraining/react-router/issues/707#issuecomment-70522213:

>> Is this really such a mess?
>
> Yes.

If you're in the middle of a project with complex scroll management requirements right now, I'd love to hear about it and/or see your proposed solutions. The v4 API is much more modular than past versions, so it should be a lot easier than it used to be to get in and alter how the router works simply by inserting components into the tree. I've got a POC that currently preserves the scroll position on `document.body`, but some apps have more strenuous requirements than that.

/cc @gaearon @ryanflorence @taurose because reading through those old issues made me remember those days when we were just getting started on this project very fondly 💕

**Comment by luke-john** [comment] 2017-02-13 05:39
We decided to adopt react-router 4 around the second alpha and went to production at around alpha-5

The key stakeholders of our site were happy for us to land with a solution that simply scrolled to top on a forward navigation, which was very [simple to implement](https://gist.github.com/luke-john/31496dadf97b8b753ca3dc4b052e1c2b) with the v4 API. 👍 

We are currently looking at updating to the beta and as part of that we will be looking at implementing the following scroll behaviors.

Upon navigating to a content page, scrolling to the content in the page (skipping header)

Ensuring on backwards navigation, with fresh state being used to render, the user is ether;
* if state change is not related to main content -> send to the same section rather than exact scroll position.
* if state change is related to main content -> send to top of content where update will be obvious

The v4 api has been a pleasure to work with so far.

**Comment by mjackson** [comment] 2017-02-13 20:54
Related: scroll restoration is [coming to browsers](http://majido.github.io/scroll-restoration-proposal/history-based-api.html#design) through a proposed addition to the HTML5 history API. Something to keep in mind.

**Comment by apostolos** [comment] 2017-02-14 01:49
*Poor man's scroll restoration:*

On [lwjgl.org](https://www.lwjgl.org) we code-split (webpack 2) each route so we have to wrap every route component with https://github.com/LWJGL/lwjgl3-www/blob/master/client/routes/asyncRoute.js

It was natural to put the scroll restoration code there. Our approach is very simple and it uses the generated [location.key](https://github.com/ReactTraining/history/blob/master/modules/createBrowserHistory.js#L66-L67) to remember the scroll position. If we get a POP action we restore the previous scroll position otherwise we scroll to top. It works really well for a simple content website.

Caveats:
- It does not implement a limit on scroll locations stored. (should it?)
- Loses state if page is reloaded, but I suppose it can easily be extended to use *sessionStorage*.
- Loses state when navigating to external links. This probably needs a scroll listener similar to [scroll-behavior](https://github.com/taion/scroll-behavior/blob/master/src/index.js#L44).
- On first navigation [location.key](https://github.com/ReactTraining/history/blob/master/modules/createBrowserHistory.js#L66-L67) prop is undefined. I don't know if that's by design or a bug. We [work around it](https://github.com/LWJGL/lwjgl3-www/blob/master/client/routes/asyncRoute.js#L96) by giving it a default value of "root".

A cleaned-up version of the HOC can be found here: https://gist.github.com/apostolos/7001146c5437368eef2d281f9ecfb3c8

**Comment by cjke** [comment] 2017-02-14 02:01
We're in the final week before launching a beta of our next app that relies heavily on RR4 (we've been confident enough in the RRv4 changes that warranted using a alpha/beta version in our app). 

As mentioned above, the accepted solution in this question http://stackoverflow.com/questions/40217585/in-react-router-v4-how-does-one-link-to-a-fragment-identifier has been working perfectly for us - we've had no issues with it so far, and works well. 

I understand its only a piece of the pie, as it addresses only the jump to a fragment identifier part of the problem, but is still useful regardless.

**Comment by ryanflorence** [comment] 2017-02-20 21:09
I wanted to jot down some thoughts on scroll management. I've implemented it several times as the router (and its beta releases) have changed over the last couple of years. I've implemented it as components outside of the router, inside of the router, inside of the `history` lib, and with raw DOM.

#### Do we need it?

I'm not sure we need to do anything about it (😂). Browsers are starting to handle scroll restoration with `history.pushState` on their own in the same manner they handle it with normal browser navigation. It already works in chrome and it's really great.

Scroll Restoration Spec: https://majido.github.io/scroll-restoration-proposal/history-based-api.html#web-idl

Most of the time all you need is to "scroll to the top" because you have a long content page, that when navigated to, stays scrolled down. That's easy, this will scroll up your entire app on every navigation:

```jsx
class ScrollToTop extends Component {
  componentDidUpdate(prevProps) {
    if (this.props.location !== prevProps.location) {
      window.scrollTo(0, 0)
    }
  }

  render() {
    return null
  }
}

const ScrollToTopOnNav = () => (
  <Route component={ScrollToTop}/>
)

// Then render it at the top of your app
const App = () => (
  <div>
    <ScrollToTopOnNav/>
  </div>
)
```

Or you could do it in just the components that need it when they mount:

```jsx
class ScrollToTopOnMount extends Component {
  componentDidMount(prevProps) {
    window.scrollTo(0, 0)
  }

  render() {
    return null
  }
}

class LongContent extends Component {
  render() {
    <div>
      <ScrollToTopOnMount/>
      <h1>Here is my long content page</h1>
    </div>
  }
}

// somewhere else
<Route path="/long-content" component={LongContent}/>
```

#### So what about a more robust generic solution? We're talking about two things:

1. Scrolling up on navigation so you don't start a new screen scrolled to the bottom
2. Restoring scroll positions of the window and overflow elements on "back" and "forward" clicks (but not Link clicks!)



For a generic API I was headed toward this:

```jsx
<Router>
  <ScrollRestoration>
    <div>
      <h1>App</h1>

      <RestoredScroll id="bunny">
        <div style={{ height: '200px', overflow: 'auto' }}>
          I will overflow
        </div>
      </RestoredScroll>
    </div>
  </ScrollRestoration>
</Router>
```

First, `ScrollRestoration` would scroll the window up on navigation. Second, it would use `location.key` to save the window scroll position *and* the scroll positions of `RestoredScroll` components to `sessionStorage`. Then, when `ScrollRestoration` or `RestoredScroll` components mount, they could look up their position from `sessionsStorage`.

What got tricky for me was defining an "opt-out" API for when I didn't want the window to scroll to be managed. For example, if you have some tab navigation floating inside the content of your page you probably *don't* want to scroll to the top (the tabs might be scrolled out of view!).

When I learned that chrome manages scroll position for us now, and realized that different apps are going to have different scrolling needs, I kind of lost the believe that we needed to provide something--especially when usually people just want to scroll to the top (which you saw is trivial to add to your app on your own).

So, yeah ... I'm not sure we need it but that API I just showed above would be pretty straightforward to implement (assuming you have a good wrapper around session storage!). I no longer feel strongly enough to do the work myself (plenty other things for me to work on!) but I'd love to help anybody who feels inclined. A solid solution would even live in this monorepo and be an official package. Hit me up if you get started on it :)

**Comment by mjackson** [comment] 2017-02-22 01:17
@ryanflorence Maybe we just add `<ScrollToTop>` to `react-router-dom` with some docs that link back to this issue and call it good?

**Comment by Andreyco** [comment] 2017-02-22 10:56
I second @mjackson's opinion. `<ScrollToTop>` component is enough, it will cover most of everyone's needs. If someone needs specific/non-default behaviour, there is high change it's project specific and RR has no change to cover that. As mentioned, browsers are starting to support scroll restoration API natively, we should make use of that instead.

**Comment by mjackson** [comment] 2017-03-08 01:46
This would make a great PR for someone who wants to go for it.

**Comment by spicydonuts** [comment] 2017-03-08 07:06
This is what we've been using for a few weeks now: https://gist.github.com/spicydonuts/d1ca3d78b9448004455562af1f04f81e

It's not real pretty but it behaves close to how you'd expect the browser to, all contained in one component.  It also means other components which get `location` passed in can inspect that scroll state.

**Comment by ryanflorence** [comment] 2017-03-10 23:38
Alright, doc is written so I can close this now :)

**Closed by ryanflorence** 2017-03-10 23:38 UTC
Labels: discussion

**Comment by cjke** [comment] 2017-03-11 01:17
The docs look really awesome. Can I confirm that scrolling to a fragment identifier is outside of scope of the docs, the library and this issue?

**Comment by rafrex** [comment] 2017-03-14 19:08
For basic scroll to `#hash-fragment` functionality I created a `HashLink` component that you can install from npm (it wraps RRv4's `Link` component). This is based on the [solution for RRv2/3](https://github.com/ReactTraining/react-router/issues/394#issuecomment-220221604).

Live example: http://react-router-hash-link.rafrex.com
Repo: https://github.com/rafrex/react-router-hash-link

When you click on a link created with `react-router-hash-link` is will scroll to the element on the page with with the `id` that matches the `#hash-fragment` in the link.

```shell
$ npm install --save react-router-hash-link
```

```javascript
// In YourComponent.js
...
import { HashLink as Link } from 'react-router-hash-link';
...
// Use it just like a RRv4 link:
<Link to="/some/path#with-hash-fragment">Link to Hash Fragment<Link>
```

**Comment by ryanflorence** [comment] 2017-03-16 06:55
maybe it varies by browser, but with `<BrowserRouter/>` hash links just work for me.

**Comment by rafrex** [comment] 2017-03-16 16:20
@ryanflorence, it doesn't seem to work for me in chrome/safari/firefox. I created a branch of the example site using Browser Router and the Link component to test it out. Can you give it a try and let me know if you get different results. Thanks.
https://github.com/rafrex/react-router-hash-link/tree/browser-router-link
```shell
$ git clone -b browser-router-link https://github.com/rafrex/react-router-hash-link.git
$ npm install
$ npm start
```
The site will be available on port `80080`

**Comment by sw-yx** [comment] 2017-09-14 19:21
hi guys can i please request an update on this what is the canonical way to do this now?

**Comment by trevorr** [comment] 2018-10-24 23:10
In case anyone finds it useful, I created a React scroll management library to address the various issues mentioned here:

1. Scrolling to top on navigation to a new page (aka the easy part)
2. Scroll restoration on history back/forward, with support for delayed/asynchronous rendering
3. Scrolling to a specific element when navigating to a hash link, also with support for delayed/asynchronous rendering

Please give it a try and submit issues/PRs if you find any issues:

https://github.com/trevorr/react-scroll-manager

It targets React 16 and supports React Router 4, though it's actually agnostic to the router (except that it indirectly uses the [`history`](https://github.com/ReactTraining/history) library underlying React Router). It's based on the ideas behind @ryanflorence's [react-router-restore-scroll](https://github.com/ryanflorence/react-router-restore-scroll) component for React Router 3 and @gajus's https://github.com/ReactTraining/react-router/issues/394#issuecomment-313120204 solution for hash link scrolling.
