### ISSUE TITLE
[v6] useParams in parent route does not contain child route params

### ISSUE THREAD

**Issue by andrelandgraf** [ReactTraining/react-router#7881] opened 2021-06-21 17:27 UTC
I noticed some unexpected behaviour of `useParams`. I also reported a very similar issue for [useSearchParams](https://github.com/ReactTraining/react-router/issues/7880) but this time, I am more certain it's actually an bug and not just an edge case.

I try to manage layouts in higher-order routes and make use of `<Outlet />` to reuse the same layout within all sub-routes. I try to use `useSearchParams` and `useParams` in the parent route to be context aware, e.g. show a different nav-menu based on which route/URL is actually rendered right now. 

## Version

v6

## Test Case

https://codesandbox.io/s/useparams-react-router-v6-ky20d?file=/src/App.js

## Steps to reproduce

Call `useParams` in a parent-route and log the result. It will miss all params of its child routes.

## Expected Behavior

`useParams` always returns all params of the current URL regardless of from where / which context it was called.

## Actual Behavior

```js
// in /projects.ts
const { projectId } = useParams();
console.log(projectId)
// would print undefined
```

(see the test case above)

**Comment by myNameIsDu** [comment] 2021-06-22 03:29
https://github.com/ReactTraining/react-router/issues/7803#issuecomment-857240176

**Comment by timdorr** [comment] 2021-06-22 03:31
Duplicate of #7803

**Closed by timdorr** 2021-06-22 03:31 UTC
