### ISSUE TITLE
All documentation site links appear to be broken (redirect to home)

### ISSUE THREAD

**Issue by gwpantazes** [ReactTraining/react-router#7611] opened 2020-09-16 15:55 UTC
# Version

The live React Router documentation site at https://reactrouter.com/web/ as of 2020-09-16.
Not sure if this corresponds to v5.2.0 or no version at all.

(BTW, I'd just like to point out that it's a bit unclear where/how to post a documentation or website bug. I do see `website` in this repository, but the bug template doesn't really treat a doc bug like a first class citizen? And the docs don't point to the github so it was unclear.)

## Test Case

Click on an intra-doc link on any documentation page, e.g. https://reactrouter.com/web/api/location
The link should go to the appropriate documentation location.

## Steps to reproduce

1. Go to https://reactrouter.com/web/api/location
2. Click on a link to some other part of the react router doc, such as the link to the Route component.
3. Observe that the link redirected to the home page, rather than going to the Route Component.

## Expected Behavior

Links would go to their intended destination in the docs.

## Actual Behavior

All links in the documentation go to the react router home page.

**Comment by timdorr** [comment] 2020-09-16 18:43
Duplicate of #7484

**Closed by timdorr** 2020-09-16 18:43 UTC
