### ISSUE TITLE
react-router-dom yarn install issue 

### ISSUE THREAD

**Issue by niyaza3** [ReactTraining/react-router#6642] opened 2019-03-18 14:16 UTC
my package.json file has

    "react-router-dom": "4.2.0"

and the node_modules/react-router-dom/package.json has 

     "dependencies": {
       "history": "^4.7.2",
       "invariant": "^2.2.2",
       "loose-envify": "^1.3.1",
       "prop-types": "^15.5.4",
       "react-router": "^4.2.0"
      }

two days ago react-router upgraded their version to 4.4.0, because of the ^ symbol the latest version 4.4.0 is installed and the application crashes as the react-router-dom itself not updated for react-router.

**Comment by timdorr** [comment] 2019-03-18 14:23
Dupe of #6630

**Closed by timdorr** 2019-03-18 14:23 UTC
