### ISSUE TITLE
Miss location is undefined

### ISSUE THREAD

**Issue by superserg8** [ReactTraining/react-router#4025] opened 2016-10-10 15:32 UTC
## Version
4.0.0-alpha.4

## Test Case
http://jsbin.com/tuvoqobaqa/7/edit?html,js

## Steps to reproduce
Click 'Will Not Match' link

## Expected Behavior
You should see location

## Actual Behavior
Location is null

**Comment by timdorr** [comment] 2016-10-10 16:45
Dupe of #4018

**Closed by timdorr** 2016-10-10 16:45 UTC
