### ISSUE TITLE
"Examples" doc sections blank/broken

### ISSUE THREAD

**Issue by jayphelps** [ReactTraining/react-router#7215] opened 2020-03-25 04:54 UTC
All the pages under the the EXAMPLES section for Web/Native appear to be broken for me.

e.g. https://reacttraining.com/react-router/web/example/basic

Might be a red herring but I see these two errors, so maybe codesandbox changed their CORS policy:

```
Failed to load resource: net::ERR_FAILED
basic:1 Access to fetch at 'https://codesandbox.io/api/v1/sandboxes/define?json=1' from origin 'https://reacttraining.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

![image](https://user-images.githubusercontent.com/762949/77503037-f4a38a00-6e32-11ea-9414-8d5e3bbdc6a8.png)

![image](https://user-images.githubusercontent.com/762949/77503022-e5244100-6e32-11ea-9cf8-b828cc6be5e2.png)

**Comment by jayphelps** [comment] 2020-03-25 04:57
If anyone else is also seeing this but needs to see the examples now, you can see them here:

Web: https://github.com/ReactTraining/react-router/tree/master/packages/react-router-dom/examples
Native: https://github.com/ReactTraining/react-router/tree/master/packages/react-router-native/examples

**Comment by timdorr** [comment] 2020-03-25 06:05
Dupe of #7213. CodeSandbox is on the fritz.

**Closed by timdorr** 2020-03-25 06:05 UTC

**Comment by jayphelps** [comment] 2020-03-25 06:15
Sorry didn’t catch it when I searched. 👍👍
