### ISSUE TITLE
withRouter wrapped component only renders when NavLink is active

### ISSUE THREAD

**Issue by penx** [ReactTraining/react-router#5141] opened 2017-05-18 18:22 UTC
## Version
4.1.1

## Test Case
https://codepen.io/penx/pen/jmeEXz

## Steps to reproduce

Create a NavLink with a child component that is wrapped with `withRouter`.

## Expected Behavior

The child component should always render when the NavLink is rendered.

## Actual Behavior

The child component only renders when the NavLink is active.

(I have a fix for this - will submit a pull request shortly)

**Comment by pshrmn** [comment] 2017-09-12 13:19
Well this issue certainly slipped through the cracks, sorry about that. It is essentially a duplicate of #4695 (which is fixed in #4704), so I think that we can safely close this.

The gist of the issue has to do with the fact that `<NavLink>` renders a `<Route children>` and `withRouter` renders a `<Route render>`. A pathless `<Route render>` uses the `match` from the context (`context.router.route.match`), and when that parent match comes from a `<Route children>` that does not match, it will be `null`. That means that when the `withRouter`'s `<Route>` renders, it will [return `null`](https://github.com/ReactTraining/react-router/blob/59a4fbc184f3a3cf4c25ee39a7e97f72efed7849/packages/react-router/modules/Route.js#L116).

**Closed by pshrmn** 2017-09-12 13:19 UTC

**Comment by penx** [comment] 2017-09-12 13:33
@pshrmn #4704 has conflicts at the moment - #5142 also fixes this (using a subset of what's done in #4704) and has a couple of unit tests not covered by #4704

**Comment by pshrmn** [comment] 2017-09-12 18:50
Yeah, either one of those should fix the issue. #4704 moves some of the functionality to `matchPath` since that is also needed for my partial `<Route>`s PR, but #5142 works as well. Hopefully this gets addressed soon; it isn't a bug that a lot of people seem to run across, but it still is annoying that it exists.
