### ISSUE TITLE
[v6] Route path matching is not intuitive: take "apple/applet" as an example

### ISSUE THREAD

**Issue by zhangdingding** [ReactTraining/react-router#7740] opened 2021-01-11 17:00 UTC
## Version

6.0.0-beta.0

## Test Case

https://codesandbox.io/s/react-router-v6-fhefl

## Steps to reproduce

In the sandbox above, click on the `Apple` and `Applet` link.

## Expected Behavior

When I click on the `Applet` link, I hope it could redirect to `NotFoundPage`, not `ApplePage`.

## Actual Behavior

When I click on the `Applet` link, it redirects to `ApplePage`. The behavior is not intuitive.

## Extra

```jsx
import React from "react";
import { BrowserRouter, Routes, Route, Navigate, Link } from "react-router-dom";

function HomePage() {
  return <div className="page">🏠 Page</div>;
}

function NotFoundPage() {
  return <div className="page">🧐 Page</div>;
}

function ApplePage() {
  return <div className="page">🍎 Page</div>;
}

export default function App() {
  return (
    <BrowserRouter>
      <div>
        <Link to="/" className="link">
          Home
        </Link>
        <Link to="/apple" className="link">
          Apple
        </Link>
        <Link to="/applet" className="link">
          Applet
        </Link>
        <Link to="/test" className="link">
          Test
        </Link>
      </div>
      <Routes>
        <Route path="/" element={<HomePage />} />
        <Route path="/404" element={<NotFoundPage />} />
        <Route path="/apple">
          <Route path="/" element={<ApplePage />} />
          <Route path="*" element={<Navigate replace to="/apple" />} />
        </Route>
        <Route path="*" element={<Navigate replace to="/404" />} />
      </Routes>
    </BrowserRouter>
  );
}
```

**Comment by timdorr** [comment] 2021-01-11 17:48
Duplicate of #7529

**Closed by timdorr** 2021-01-11 17:48 UTC

**Comment by zhangdingding** [comment] 2021-01-12 02:42
Hi, Tim, I already looked at #7529 before opening this issue. I think this issue is a little different from that one, therefore I opened a new one.
