### ISSUE TITLE
Prompt

### ISSUE THREAD

**Issue by GOVYANSONG** [ReactTraining/react-router#7212] opened 2020-03-24 14:59 UTC
## Version

V4

## Test Case 1

User tries to navigate away from current screen, prompt displayed and user cancels the navigation

## Steps to reproduce

Navigate to a form;
Edit data elements on the form;
Click on Back button of Chrome;
Prompt displayed a warning message;
User decides to remain on current form by clicking Cancel button on the prompt;

## Expected Behavior

User should only be prompted exactly once and remain on current screen.

## Actual Behavior

As expected.

## Extra info

I noticed that the URL address bar was updated to the previous location while the prompt is being displayed. Once user clicked on Cancel button on the prompt, the URL address was reverted back to the current screen. Also, it was observed in redux devtools that ROUTER@LOCATION_CHANGE was trigger whenever the browser Back button was clicked.

## Test Case 2

User tries to navigate away from current screen, prompt displayed and user cancels the navigation

## Steps to reproduce

Navigate to a form;
Edit data elements on the form;
Click on navlink of another screen within the same SPA;
1st Prompt displayed a warning message;
User decides to remain on current form by clicking Cancel button on the prompt;
2nd Prompt displayed the same warning message again;
User has to click again the Cancel button to remain on the current form;

## Expected Behavior

User should only be prompted exactly once and remain on current screen.

## Actual Behavior

User was prompted with the same message twice.

## Extra info

I noticed that the URL address bar was never updated to previous location during the prompt. Also, it was observed that no ROUTER@LOCATION_CHANGE was triggered.

**Comment by timdorr** [comment] 2020-03-24 17:29
Duplicate of #5405

**Closed by timdorr** 2020-03-24 17:29 UTC
