### ISSUE TITLE
Issue with latest react router dom

### ISSUE THREAD

**Issue by ramya222** [ReactTraining/react-router#6935] opened 2019-09-26 13:49 UTC
Hi Team,
Because of latest react-router-dom when we do npm install application itself is breaking as it was saying "Stateless function component cannot have refs". This issue is in Link module where ref is going as a empty object. Due to this latest version whole application is not working. Please suggest us  to resolve the issue.

**Comment by timdorr** [comment] 2019-09-26 15:30
Duplicate of #6934

**Closed by timdorr** 2019-09-26 15:30 UTC
