### ISSUE TITLE
React router website, quick start page can't scroll

### ISSUE THREAD

**Issue by heldrida** [ReactTraining/react-router#3873] opened 2016-09-16 09:23 UTC
React router website, quick start page can't scroll

https://react-router-website-xvufzcovng.now.sh/quick-start

**Comment by femesq** [comment] 2016-09-16 12:58
Confirmed here (Chrome v53 on MacOS).

In `Inspector`, removing `height: 100%;` from `<div id="app">` solved the problem... 

Tested on Firefox and Safari, and both are working...

**Comment by katpas** [comment] 2016-09-16 13:01
Looks like none of the pages scroll if you're using Chrome or Firefox. It's fine on Safari. I opened up the browser console and unticked the body height property which is set to 100%. Brought back the scroll bar.

**Comment by timdorr** [comment] 2016-09-16 15:06
Dupe of #3859. Fixed in e12f607.

**Closed by timdorr** 2016-09-16 15:06 UTC
