### ISSUE TITLE
Unexpected difference between clicking a <Link> or clicking the back button

### ISSUE THREAD

**Issue by deiucanta** [ReactTraining/react-router#5072] opened 2017-05-04 18:00 UTC
## Test Case
https://codesandbox.io/s/G6nWE3X0r

## Steps to reproduce

- click on "page 1" link
- click on "back to home" link
- click on "page 2" link
- press the browser's back button

## Expected Behavior

It should go back to `/`.

## Actual Behavior

It's stuck showing "page 2".

---

The `<App>` component is not blocking the update since it has the 'location' injected via the `connect()` function. However, if I change `connect()` to `withRouter()` it works. 

Also, when I remove the `<Switch>` component the back button works as expected.

**Comment by pshrmn** [comment] 2017-05-04 18:22
@deiucanta You can safely ignore this comment.

@timdorr I went ahead and made a `react-router-redux` label so that issues/PRs for it can be easily identified. If you don't want this, feel free to remove it, but I thought that it could be helpful. Another label for `react-router-config` could probably also be made (and maybe the other packages as well).

**Comment by timdorr** [comment] 2017-05-04 18:33
@pshrmn I had created Projects for all of them, but they aren't really that easy to use I've found. The labels work better.

@deiucanta That appears to be a side effect of using that site. I guess their browser emulation isn't complete or to spec.

**Comment by deiucanta** [comment] 2017-05-04 18:50
@timdorr I initially got this behaviour working a project on my local machine and then I replicated it in codesandbox.io. Please reopen the issue and let me know if you have other hints on where the issue might be.

**Comment by taurose** [comment] 2017-05-04 21:13
Getting the same behavior after downloading and running it locally.

I looked into it a bit, and I think the main problem is that, while both `<ConnectedRouter>` and `<Router>` subscribe to history, `<ConnectedRouter>` is called first, causing the app to update with the old route before `<Router>` gets a chance to update the context of the app. The update that would then be caused by `<Router>` is prevented by `connect(..)` (sCU), because the store's location hasn't changed.

The reason it works on the first transition (clicking Page x) is that React batches the first update since the update results from an event handled by React, so `connect(..)` will only be rendered once at the end and not block any updates. 

When appending `setTimeout(() => history.push('/page/2'))` to `index.js`, for example, it doesn't properly update either as there is no batching of the two updates.

**Comment by deiucanta** [comment] 2017-05-04 21:46
@taurose Inspecting with ReactDevTools I can see that `<App>`s location prop is changing when I hit the back button but inside the `<Switch>` it matches the previous route.

The component structure is like this

```
<ConnectedRouter>
  <Router>
    <App>
      <Switch>
```

On a regular location change, this is what happens

1. `ConnectedRouter` listens to history and it dispatches a redux action to change the location in store
2. `Router` listens to history and updates the context values
3. `App` listens to the redux store and updates because there is a new location

So, you're basically saying that step 3 somehow happens before step 2 and when the `Router` updates the context values is too late because `App` will not render again since the props don't change.

Am I right? Should this be fixed in the library or should I change my code to make it work?

**Comment by timdorr** [comment] 2017-05-05 01:00
@taurose Thanks for the investigation. This sounds like a legit bug with the library.

@deiucanta Sorry for the fast close. It's still in alpha, so things like this need to be worked out.

**Comment by chrismllr** [comment] 2017-05-05 20:12
Hey guys - can confirm another case of this... I've noticed the location object within the `router` reducer Does change, so I am able to assert there is a discrepancy between the two and call a `history.go()` in the meantime

**Comment by taurose** [comment] 2017-05-05 23:04
@deiucanta Yep, that sums it up well.

I think it should work fine with controlled `<Route>`s, `<Switch>`es and `<NavLink>`s (ie. passing `location` as a prop to them yourself). Seems more reasonable to me anyways,

**Comment by pmwisdom** [comment] 2017-05-10 23:01
I think I was having this same problem and "solved" this for myself by connecting my switches to the store. Or you could pass the router location down through its props manually (since Switch allows you to pass in your own location object).

````
import {connect} from 'react-redux';
import {Switch} from 'react-router';

const mapStateToProps = state => {
	return {location: state.router.location};
};

const ConnectedSwitch = connect(mapStateToProps)(Switch);

export default ConnectedSwitch;
````

**Comment by IljaDaderko** [comment] 2017-05-12 17:56
@pmwisdom Came to same solution as well. However, to me it feels like Switches wrapped in `ConnectedRouter` should do this on their own.

**Comment by deiucanta** [comment] 2017-05-12 18:12
@IljaDaderko totally agree

**Comment by deiucanta** [comment] 2017-05-24 16:11
@timdorr did you manage to look into this? If you give me some guidance I'm happy to make a PR.

**Comment by dak0rn** [comment] 2017-05-30 09:52
I think I have the same problem.

I use `react-router` with the Redux package in a web application. I noticed
the same behaviour; when using `<Link />`s, routes are rendered correctly.
Upon using the back button, the UI is one step behind (pressing back again
renders the page it should have rendered in the first step).

I added logging statements to `Route`, `Router` and my component wrapper.
Upon clicking a `<Link />`, the order of operations looks as follows:

<img width="860" alt="normal" src="https://cloud.githubusercontent.com/assets/3854533/26577593/2f259b50-452d-11e7-9984-ae530cd8fc65.png">

The child context is updated with the new location and all `<Route />`s rerender.

When using the back button, however, it looks differently:

<img width="876" alt="back" src="https://cloud.githubusercontent.com/assets/3854533/26577601/3477fc10-452d-11e7-841f-59ee7bb9f1e3.png">


All `Route`s are rerendered first, the context (`context_path`) contains the old
path while `history` contains the correct path (`actual_path`). The context providing
the former is updated like in the middle.

The location is set correctly in the Store, by the way, so the navigation highlights
the actual path while the _main_ UI is not updated.

I do not really have an idea, yet, why the order is different. It is also interesting
that the route contained in the route for `/admin` also gets the wrong path
through context although `getChildContext` was already invoked (last three lines).

### Why does it help to connect `Switch`?

Because it [passes down the `location` prop](https://github.com/ReactTraining/react-router/blob/master/packages/react-router/modules/Switch.js#L51) which is then [used by `Route` instead of context](https://github.com/ReactTraining/react-router/blob/master/packages/react-router/modules/Route.js#L56).

**Comment by Geoff-Ford** [comment] 2017-06-01 22:51
FYI: I have been having the same issue but with react-router-redux v5 and react-router-dom. The suggestion from @pmwisdom to create a `ConnectedSwitch` container component and swapping this in place of `Switch` resolves the issue.

**Comment by hawksdoves** [comment] 2017-06-05 10:15
Experiencing this as well.

Using ‘react-router-redux’, the <ConnectedRouter> location state/prop is updating correctly as route changes. However, the location prop passed to the <Route> render methods are not updating in-sync. Example: after pressing the back button, the location.pathname has not been updated and will continue to be out of sync by one, such that when using <Route children={match}>  you can see that match returns null, when the route does actually match.

As previously mentioned, in the mean time passing down location from the connectedRouter as a prop to <Route> etc will solve this problem.

**Comment by kamronbatman** [comment] 2017-06-21 16:10
@Geoff-Ford, Can you set up a gist with your `ConnectedSwitch` code? I would love to see how you did the workaround.  Thanks!

**Comment by deiucanta** [comment] 2017-06-21 19:42
```
import { connect } from 'react-redux'
import { Switch } from 'react-router-dom'

const mapStateToProps = state => ({
  location: state.router.location,
})

const ConnectedSwitch = connect(mapStateToProps)(Switch)

export default ConnectedSwitch
```

**Comment by kamronbatman** [comment] 2017-06-21 21:58
Thanks @deiucanta.  After I posted that comment, I did find this (which is similar).
[ConnectedSwitch.js](https://github.com/team-griffin/react-router-connected/blob/develop/src/ConnectedSwitch.js)

**Comment by Geoff-Ford** [comment] 2017-06-22 08:46
Sorry for the tarde response. What @deiucanta has provided there is exactly the same as I have implemented too.

**Comment by timdorr** [comment] 2017-07-12 04:17
I wonder if #5203 fixed this unintentionally...

**Comment by DanHarman** [comment] 2017-07-19 16:16
I hit this too on a set of Routes outside a switch. So I guess it means a ConnectedRoute is needed if there isn't a cleaner fix.

Just goes to show why context is not recommended by the react team!

**Comment by comerc** [comment] 2017-07-21 09:31
My 50 cents. Do not send location to Switch:

```javascript
import React from 'react'
import { connect } from 'react-redux'
import { Switch, Route } from 'react-router-dom'

const addLocation = connect(state => ({
  location: state.routing.location,
}))

export const ConnectedSwitch = addLocation(({ location, ...props }) => <Switch {...props} />)
export const ConnectedRoute = addLocation(props => <Route {...props} />)
```

**Comment by davidcalhoun** [comment] 2017-07-27 15:49
Thanks @pmwisdom!  I thought I was going nuts!  I ended up using method #2, passing location directly to Switch, and it seems to work fine:

```js
          <Switch location={this.props.location}>
            {routes}
          </Switch>

...

const mapStateToProps = state => ({
  location: state.router.location
});

```

**Comment by solominh** [comment] 2017-09-04 15:32
I have came across this library and article (from Facebook docs recommendation)
https://github.com/ReactTraining/react-broadcast
https://medium.com/@mweststrate/how-to-safely-use-react-context-b7e343eff076

I have a question: Have react-router started using this observable pattern yet?
I've looked for it in react-router V4 source code but apparently react-router haven't applied it yet.

**Comment by athomann** [comment] 2017-09-07 01:33
@timdorr I upgraded `react-router-dom` from `4.1.1` to `4.2.2` and the issue goes away.  https://codesandbox.io/s/8kww21oyrl

Might be able to close this issue.

**Comment by athomann** [comment] 2017-09-07 01:41
@timdorr this may be because of the `connect` in `App.js`.  Adding `withRouter` on `export default withRouter(connect(mapStateToProps)(App));`  fixes the issue.

**Comment by SadPandaBear** [comment] 2017-09-12 03:59
I wonder if we should be creating the ConnectedSwitch everytime we want to provide a Switch in order to not to mess up with the connected location state or open up a pull request so React Router Redux can provide it's own ConnectedSwitch?

**Comment by jduthon** [comment] 2017-09-20 15:04
Another related bug : https://codesandbox.io/s/z6ozxy053
Following the same process (so first clicking on Page X, then going back with the browser back button), the Page component will be rendered with an incorrect location for a moment ('/') before unmounting.
Which is kind of annoying when you are relaying on router state to display components which need props from the route. Then you need to add some extra protection on said components because the unmounting will only happen later.

As for the ConnectedSwitch, I believe it would work, but I am also using react-router-config, which uses Switch internally in renderRoutes, and I don't know of a way to pass your own location object to the underlying switch in ConnectedSwitch.

**Comment by iiiyx** [comment] 2017-09-24 16:32
There are 2 history records appeared in browser history with the same location when I use `store.dispatch(push(url))` or `browserHistory.push(url)`
But this only happens in level 2 nested router component ComponentLvl2.
Pseudo code:
`<ConnectedRouter>
  <Route path="/" component=App>
    <ConectedSwitch>
      <Router path="/level1" render=ComponentLvl1>
        <ConnectedSwitch>
          <Router path="/level1/level2" render=ComponentLvl2 />
        </ConnectedSwitch>
      </ComponentLvl1>
    </ConectedSwitch>
  </App>
</ConnectedRouter>`

As you can see, I use ConnectedSwitch workaround, but this doesn't help with the issue. 
Also I can mention that this happens also with react-router v3

**Comment by kesha-antonov** [comment] 2017-12-18 21:40
Anybody uses mobx? How to fix it with mobx?

**Comment by fterradev** [comment] 2017-12-20 15:07
Do I have to create a "router" reducer in order to use this ConnectedSwitch?
I've just tried the code provided [here](#issuecomment-300636461) by @pmwisdom but it failed with:

Uncaught TypeError: Cannot read property 'location' of undefined
    at Function.mapStateToProps [as mapToProps] (ConnectedSwitch.js:6)

What should I do to make it work?

**Comment by mahaina** [comment] 2017-12-29 06:11
anybody got a final solution? same problems here...

**Comment by timdorr** [comment] 2018-06-06 16:03
Closing this out since react-router-redux is deprecated. Use [connected-react-router](https://github.com/supasate/connected-react-router) instead!

**Closed by timdorr** 2018-06-06 16:03 UTC
Labels: react-router-redux
