### ISSUE TITLE
[v6] Add inactive class and style to NavLink

### ISSUE THREAD

**Issue by beaussan** [ReactTraining/react-router#7675] opened 2020-10-30 13:29 UTC
It would be great to implement inactiveClassName and activeClassName into the NavLink. It would be easier to distinguish the styles to apply, especially using tailwindcss.

The way I'm doing it in my application is to copy the code of the NavLink, adding the two props and remplace the two null in conditionals with the inactive styles / class.

Do you think I can submit a pr for this?

I have been using the v6 since the first alpha, and it's the only thing that's bugs me ! Great work on v6 !

**Comment by timdorr** [comment] 2020-11-02 17:06
Duplicate of #7194

**Closed by timdorr** 2020-11-02 17:06 UTC

**Comment by tjunghans** [comment] 2020-11-23 08:50
I would also appreciate this possibility. Any chance of accepting @beaussan PR?

**Comment by beaussan** [comment] 2020-11-23 08:52
If you need it, I just embed the component in my project, it's the same component, with the inactive class and style added :

```tsx
import React from 'react';
import { useLocation, useResolvedPath } from 'react-router';
import { Link, LinkProps } from 'react-router-dom';

/**
 * A <Link> wrapper that knows if it's "active" or not.
 * Rip from https://github.com/ReactTraining/react-router/blob/v6.0.0-beta.0/packages/react-router-dom/index.tsx
 * However since they wont include the inactive class and style, here is the implementation, based on their NavLink
 * See https://github.com/ReactTraining/react-router/issues/7194
 */
export const ActiveNavLink = React.forwardRef<
  HTMLAnchorElement,
  ActiveNavLinkProps
>(function ActiveNavLinkWithRef(
  {
    'aria-current': ariaCurrentProp = 'page',
    activeClassName,
    activeStyle,
    inactiveClassName,
    inactiveStyle,
    caseSensitive = false,
    'className': classNameProp = '',
    end = false,
    'style': styleProp,
    to,
    ...rest
  },
  ref,
) {
  let location = useLocation();
  let path = useResolvedPath(to);

  let locationPathname = location.pathname;
  let toPathname = path.pathname;
  if (!caseSensitive) {
    locationPathname = locationPathname.toLowerCase();
    toPathname = toPathname.toLowerCase();
  }

  let isActive = end
    ? locationPathname === toPathname
    : locationPathname.startsWith(toPathname);

  let ariaCurrent = isActive ? ariaCurrentProp : undefined;
  let className = [
    classNameProp,
    isActive ? activeClassName : inactiveClassName,
  ]
    .filter(Boolean)
    .join(' ');
  let style = { ...styleProp, ...(isActive ? activeStyle : inactiveStyle) };

  return (
    <Link
      {...rest}
      aria-current={ariaCurrent}
      className={className}
      ref={ref}
      style={style}
      to={to}
    />
  );
});

export interface ActiveNavLinkProps extends LinkProps {
  activeClassName?: string;
  activeStyle?: object;
  inactiveClassName?: string;
  inactiveStyle?: object;
  caseSensitive?: boolean;
  end?: boolean;
}
```

**Comment by fubhy** [comment] 2020-12-07 20:23
@timdorr I'd have to agree with the previous comments here. The `inactiveClassName` prop is imho desirable especially considering the popularity of Tailwind and other CSS frameworks but also simply because relying on the order of class names instead of switching them out is simply not bulletproof. In cases where the CSS declarations are outside of your control, not having sth. like `inactiveClassName` makes it impossible to use the default `NavLink` component.

**Comment by nessor** [comment] 2021-08-13 08:08
Is there anything new on this? I also see it like @fubhy that when using Tailwind CSS such a feature would be really useful.. In fact, that's exactly the problem we have right now.
Looking into the code, the tweak would also be done really fast.
https://github.com/ReactTraining/react-router/blob/1aacf7857e60eadd94dbbb22f3e51e54ba590b56/packages/react-router-dom/modules/NavLink.js#L71-L73

@timdorr  would you accept a PR?

**Comment by nessor** [comment] 2021-08-14 15:16
In case anyone needs it. We(@christian98) have copied the NavLink component and extended it accordingly.

Here is the component in TypeScript. Maybe it will help someone.

```typescript
import React from "react";
import {__RouterContext as RouterContext, matchPath} from "react-router";
import invariant from "tiny-invariant";
import {Link, LinkProps, NavLinkProps} from "react-router-dom";
// @ts-ignore
import { resolveToLocation, normalizeToLocation} from "react-router-dom/modules/utils/locationUtils";


function joinClassnames(...classnames: (string | undefined)[]) {
    return classnames.filter(i => i).join(" ");
}

export interface EnhancesNavLinkProps extends NavLinkProps {
    /**
     * Will be chosen if the link is not active.
     */
    inactiveClassName: string,
    sensitive?: boolean | undefined
}

/**
 * A <Link> wrapper that knows if it's "active" or not.
 */
const EnhancedNavLink =
    ({
         "aria-current": ariaCurrent = "page",
         activeClassName = "active",
         inactiveClassName = "inactive",
         activeStyle,
         className,
         exact,
         isActive: isActiveProp,
         location: locationProp,
         strict,
         sensitive,
         style: styleProp,
         to,
         innerRef,
         ...rest
     }: EnhancesNavLinkProps) => {
        return (
            <RouterContext.Consumer>
                {context => {
                    invariant(context, "You should not use <NavLink> outside a <Router>");

                    const currentLocation = locationProp || context.location;
                    const toLocation = normalizeToLocation(
                        resolveToLocation(to, currentLocation),
                        currentLocation
                    );
                    const {pathname: path} = toLocation;
                    // Regex taken from: https://github.com/pillarjs/path-to-regexp/blob/master/index.js#L202
                    const escapedPath =
                        path && path.replace(/([.+*?=^!:${}()[\]|/\\])/g, "\\$1");

                    const match = escapedPath
                        ? matchPath(currentLocation.pathname, {
                            path: escapedPath,
                            exact,
                            sensitive,
                            strict
                        })
                        : null;
                    const isActive = !!(isActiveProp
                        ? isActiveProp(match, currentLocation)
                        : match);

                    const CalculatedClassName = isActive
                        ? joinClassnames(className, activeClassName)
                        : joinClassnames(className, inactiveClassName);
                    const style = isActive ? {...styleProp, ...activeStyle} : styleProp;

                    const props: LinkProps = {
                        "aria-current": (isActive && ariaCurrent) || "page",
                        className: CalculatedClassName,
                        style,
                        to: toLocation,
                        ...rest
                    };

                    return <Link {...props} />;
                }}
            </RouterContext.Consumer>
        );
    };

export default EnhancedNavLink;
```
