### ISSUE TITLE
Link isn't rendered as active for matched routes with optional param

### ISSUE THREAD

**Issue by jimkyndemeyer** [ReactTraining/react-router#4353] opened 2017-01-19 10:01 UTC
## Version
3.0.2

## Test Case
http://jsbin.com/faziyeroti/edit?html,js,output

## Steps to reproduce
Click the "Customer id 1" link.

## Expected Behavior
The "Customers" link should be shown as active as this is the route that was matched.

## Actual Behavior
The "Customers" link is not shown as active.

**Comment by timdorr** [comment] 2017-01-19 14:31
Dupe of #3233, #3237, #3277. Please check existing issues first.

**Closed by timdorr** 2017-01-19 14:31 UTC

**Comment by jimkyndemeyer** [comment] 2017-01-19 14:52
Thanks. Did a search, but apparently not one with the right terms.

If others stumble across this issue, the solution appears to be a nested route with no component: https://github.com/ReactTraining/react-router/issues/3277#issuecomment-209004966
