### ISSUE TITLE
[v6] basename not working for absolute navigation

### ISSUE THREAD

**Issue by zhaoyao91** [ReactTraining/react-router#7432] opened 2020-06-20 17:39 UTC
## Version

react-router-dom@6.0.0-beta.0

## Test Case

- demo site: https://gksdf.csb.app/my-base/demo
- codesandbox: https://codesandbox.io/s/react-router-v6-basename-bug-gksdf

## Steps to reproduce

- set a basename to useRoutes: https://codesandbox.io/s/react-router-v6-basename-bug-gksdf?file=/src/RoutedPage.tsx
- navigation with relative path is ok: https://codesandbox.io/s/react-router-v6-basename-bug-gksdf?file=/src/pages/Demo.tsx
- navigation with absolute path is bad, it ignores the basename: https://codesandbox.io/s/react-router-v6-basename-bug-gksdf?file=/src/pages/Demo.tsx

## Expected Behavior

- after setting basename, navigation with absolute path will respect the basename

## Actual Behavior

- after setting basename, navigation with absolute path ignores the basename

**Comment by timdorr** [comment] 2020-06-20 23:05
Dupe of #7216

**Closed by timdorr** 2020-06-20 23:05 UTC
