### ISSUE TITLE
[v6] Expose action

### ISSUE THREAD

**Issue by fluidsonic** [ReactTraining/react-router#7934] opened 2021-08-09 04:23 UTC
### What is the new or updated feature that you are suggesting?

v6 router should expose the `action` (`POP`, `PUSH`, `REPLACE`).

### Why should this feature be included?

I'm trying to migrate v5 logic to v6.
Part of the logic is "scroll to top" when navigating to a new page. For that to work correctly I must only scroll the page on `PUSH` and `REPLACE` actions but not on `POP` actions. The latter would be scroll restoration which is done by the browser.

**Comment by timdorr** [comment] 2021-08-09 15:49
Duplicate of ReactTraining/history#864

**Closed by timdorr** 2021-08-09 15:49 UTC
