### ISSUE TITLE
component wrapped by withRouter is unmounted on every re-render

### ISSUE THREAD

**Issue by marksweston** [ReactTraining/react-router#4630] opened 2017-03-04 21:00 UTC
With regard to `withRouter` in v4:

I wrapped a component with withRouter in order to get access to push.  My component maintained a small amount of state in order to manage user interactions with child components (e.g. currently selected tab).  

As soon as I added withRouter, my component started behaving strangely, and I eventually tracked it down to the fact my component, now wrapped by withRouter, was being unmounted and re-mounted every time a user interaction caused what would previously have been an update / re-render.  The result was of course that state was being lost every time.

Is this intended behaviour?  It seems to me that the implied contract of an HOC is that it adds behaviour or properties to the wrapped component without changing the previous behaviour of that component, and this side-effect breaks that contract.  It certainly makes it hard to use withRouter when one has to consider whether a) it's safe to use withRouter with any specific component and then b) worry about that component might need to change some time in the future, in a way that will make it retrospectively incompatible with withRouter.

I don't yet understand the internals of react-router very well, but I assume this behaviour is a result of the implementation of `withRouter` by rendering a `Route` and passing the wrapped component as a prop to be rendered.  Is this essential?  Presumably the problem goes away if `withRouter` accesses the ancestor Router's context and renders the wrapped component directly?

**Comment by Shaxmatist** [comment] 2017-03-04 21:21
Yes, something happened or changed with `withRouter` in beta.7. In version beta.6 everything worked correctly.

**Comment by Shaxmatist** [comment] 2017-03-04 22:33
I'm sorry, the previous comment is probably not related to this topic. But there's something really wrong with the beta.7. When routes changed, all components are not updated. While I do not understand what the problem is.

Now the question about withRouter v4.
If the `Component` wrapped by `withRouter` and url is `/items/:itemID` then match.params is always empty. Is it normal behavior? Why itemID is not available through params in `Component`?

**Comment by mjackson** [comment] 2017-03-05 03:34
> there's something really wrong with the beta.7

Are you using `react-redux` or `shouldComponentUpdate` in your route components?

**Comment by firasdib** [comment] 2017-03-05 14:53
@mjackson I am using `react-redux` and seeing the same problems as @Shaxmatist. I suppose the props aren't being compared properly and thus the components aren't updating. What specifically changed in beta7 for this to occur? Perhaps it should be changed as the current behavior seems a bit backwards and having to manually re-implement `shouldComponentUpdate` to tailor to specific things in `react-router` feels a bit tedious.

**Comment by pshrmn** [comment] 2017-03-05 15:09
Subscriptions were removed in beta 7.

Navigation re-renders should propagate from the`<Router>`, not every location aware component. If you have a component that uses `sCU` to prevent re-renders, React Router shouldn't have to try to get around that. Instead`sCU` should recognize that the `location` is different and return `true`. When it comes to `react-redux`, you can do this by passing the `location` as a prop to the connected component.

**Comment by firasdib** [comment] 2017-03-05 15:20
@pshrmn That would probably explain some of the issues I've been having, but I still can't get my app to update.

I have a Root component that renders the following only:
```js
      <Provider store={this.props.store}>
        <Router>
          <MainContainer />
        </Router>
      </Provider>
```

And then `MainContainer` contains a bunch of routes in a switch. It depends on `react-redux` so I've overwritten `shouldComponentUpdate` to always return true. Regardless of this change it does not work.

**Comment by pshrmn** [comment] 2017-03-05 15:25
Pass the `{ pure: false }` option to `connect` (fourth argument) and it should work.

**Comment by firasdib** [comment] 2017-03-05 15:56
@pshrmn That seems to have solved one of my issues, but the remounting of components (which I believe was the root of this issue) is still present.

**Comment by Shaxmatist** [comment] 2017-03-05 16:13
> Are you using react-redux or shouldComponentUpdate in your route components?

I'm using react-redux. Thanks to @pshrmn for the answer. But question about `withRouter` and `match.params` is actual.

**Comment by pshrmn** [comment] 2017-03-05 17:12
@Shaxmatist Right now, `withRouter` renders a pathless `<Route>`, which creates a new, "empty" match object. That is why your parameters are not showing up (and this is different than what would happen if you accessed the parent `match` directly through `context`, so I would consider this a bug).

Based on my work with relative routes, I believe that a pathless `<Route>` should inherit the `match` from its parent. If that is the case, then the `match` prop inside of `withRouter` would have the correct params.

**Comment by mjackson** [comment] 2017-03-06 01:38
@pshrmn Let's fix the bug and create a doc for people using `react-redux` and/or `shouldComponentUpdate`.

**Comment by marksweston** [comment] 2017-03-06 09:31
@pshrmn @mjackson 
This conversation feels like it's taken a slight tangent from my original question, if you're only looking at how match params are passed down to the component wrapped by withRouter.
Is the repeated unmounting of the wrapped component intended behaviour?  Should it be?

(my app wasn't using react-redux and the relevant component didn't define shouldComponentUpdate).

**Comment by mjackson** [comment] 2017-03-06 17:23
You're right, @marksweston. My apologies.

What beta version are you using? We recently fixed a re-mounting issue in #4592 (released in beta 7). Could be that it's already fixed.

**Comment by timdorr** [comment] 2017-03-06 17:28
Also, some example code would be *really* helpful here.

**Comment by indiesquidge** [comment] 2017-03-06 18:28
@timdorr, I'm trying to create a simple example, but can't seem to find the globally exported `ReactRouter` object. I am getting a reference error when I try and access things like `BrowserRouter` and `Route` from it. Am I missing something?

http://jsbin.com/dohoya/edit?html,js,console

**Comment by indiesquidge** [comment] 2017-03-06 18:44
It seems like [this change](https://github.com/ReactTraining/react-router/commit/1f0107986f98b38e175819fb0eca77c42c18b6bb#diff-524339bd092db50934a0c59a2df5d83dR3) was explicitly stating that only the closest `<Route>`'s `match` would be available when using `withRouter`, but it doesn't state that a pathless `<Route>` will (or should) inherit `match` from its parent in order to get access to, say, `match.params`.

Was this not the intentional behavior? I _think_ I'm agreeing with most people on this thread that it feels like a bug not to have access to params in child components using `withRouter`.

For example, when I have something like

```javascript
const Root = () => (
  <Router>
    <Route path='/:filter' component={TodoApp} />
  </Router>
)

// later
const TodoApp = () => (
  <div>
    <AddTodo />
    <VisibleTodoList />
    <Footer />
  </div>
)
```

Where, let's say, `<VisibleTodoList />` is wrapped by `withRouter`.

I should be able to access the `filter` param from within `<VisibleTodoList />`, correct?

**Comment by pshrmn** [comment] 2017-03-06 18:54
@marksweston An example would be appreciated. I am not seeing any difference in the mount/updates between a component wrapped with `withRouter` and one that is not in this [codepen](http://codepen.io/pshrmn/pen/oZzEEM)

**Comment by marksweston** [comment] 2017-03-06 22:41
@mjackson I was using beta.6, but updating to beta.7 gives me the same behaviour.

It's a bit tough to extract a readable example from our apps codebase, so I'll try to construct something in Codepen or an example app.

**Comment by marksweston** [comment] 2017-03-07 10:11
Update: So far I'm failing to come up with an example that fits easily in Codepen and reproduces the unmounting behaviour.

I can still reproduce the problem in my app at will, but have worked round it by simply removing `withRouter` and having a component that's already router-aware pass `push` down the tree as a prop.

I will have another go at creating an example app that reproduces the problem tonight.

**Comment by taurose** [comment] 2017-03-07 13:02
Some guesses:

* you call `withRouter(..)` during rendering which would create a new component class each time
* you pass a new function to `Route.component` each render, e.g. using anonymous function `<Route component={() => <div>{...}</div>} />`

**Comment by marksweston** [comment] 2017-03-07 13:57
```
  render() {
    const RoutedInvoicesTable = withRouter(InvoicesTable);
    ...
  }
```
Good guess, thank you.  At the time it seemed like a good idea to put the const declaring the component class as close as possible to where it was used, for future readability.  Doh.

I guess I'm ready to close this issue, but it did start a parallel conversation which might still be about a genuine bug.  So should I leave it open for now?

**Comment by pshrmn** [comment] 2017-03-07 16:00
The other issue has been resolved as well.

**Closed by pshrmn** 2017-03-07 16:00 UTC

**Comment by mjackson** [comment] 2017-03-07 16:31
Thanks @taurose :)

**Comment by shishircc** [comment] 2017-09-12 10:39
Thanks all. We had been pulling our hair trying to resolve this issue. This helped a lot.

**Comment by bonebizz21** [comment] 2017-09-14 22:25
Thanks to all of u

**Comment by danvoyce** [comment] 2017-10-31 17:42
Thanks @taurose! Have literally saved my last few hairs. However, if we can't pass in anonymous functions, how do we go about passing in wrapped components? Eg. 

```
export default function preload(WrappedComponent, props) {
    class Preload extends React.Component {
        componentWillMount() {
            getDataForComponent(props);
        }

        render() {
            return <WrappedComponent {...props} />;
        }
    }
    return Preload;
}
```

**Comment by danvoyce** [comment] 2017-10-31 19:20
Hey @timdorr why did you delete my previous comment? It's directly related to this issue and would help me and others out a lot
