### ISSUE TITLE
Webpage's responsive route does not work

### ISSUE THREAD

**Issue by LeonAppDev** [ReactTraining/react-router#6285] opened 2018-08-10 01:36 UTC
## Version
https://reacttraining.com/react-router/core/guides/philosophy

## Test Case
When browsing the web page using a mobile device or test in 'toggle device model'  of Chrome, the back arrow does not work, and it will make the page hanging which is a quite bad example of responsive routing.
![image](https://user-images.githubusercontent.com/10129395/43934120-c3f8924c-9ca1-11e8-9ee4-868b77e6ba31.png)

## Steps to reproduce
1 Open https://reacttraining.com/react-router/core/guides/philosophy from a mobile device or use Chrome to stimulate a mobile device,  you could see the resolution I use in Chrome from snapshot I upload in Test Case.

2 Try to click the button I tag with a red rectangle.
## Expected Behavior
Go back to Menu
## Actual Behavior
No action.

**Comment by pshrmn** [comment] 2018-08-10 02:28
Thanks for the report, @LeonAppDev. The issue is already reported in #6058, so I'm going to close this one.

**Closed by pshrmn** 2018-08-10 02:28 UTC

**Comment by LeonAppDev** [comment] 2018-08-10 04:29
Ok, thanks for quick response
