### ISSUE TITLE
[v4] Location prop not set in <Miss>

### ISSUE THREAD

**Issue by davidrossjones** [ReactTraining/react-router#4071] opened 2016-10-19 21:50 UTC
I'm using this exact code example:

https://react-router.now.sh/no-match-handling

But the`location` prop is `undefined` inside the render function of `NoMatch` component passed to `<Miss>`. What am I doing wrong? Has something changed?

**Comment by timdorr** [comment] 2016-10-19 22:33
Dupe of #4035 and #4018

**Closed by timdorr** 2016-10-19 22:33 UTC
