### ISSUE TITLE
Partially encoded parameter

### ISSUE THREAD

**Issue by edbentley** [ReactTraining/react-router#5472] opened 2017-08-28 08:28 UTC
## Version
4.2.0

## Test Case
https://codesandbox.io/s/qxv30r58m6

## Steps to reproduce
1. My app has an id string that is partially encoded, e.g. `id//github%2Fissues`
2. I encode this (using `encodeURIComponent`) to `id%2F%2Fgithub%252Fissues` in the URL.
  ```<Link to='/id%2F%2Fgithub%252Fissues'>link</Link>```
  It is still encoded in the address bar.
3. Use a path of `/:id`
4. I then receive this back as parameter `match.params.id` which when printed out is `id%2F%2Fgithub%2Fissues` (note `%252F` has become `%2F` - looks like `decodeURI` was run on it)
5. I decode it (using `decodeURIComponent`) and get `id//github/issues` back

Expected: `id//github%2Fissues`
Actual: `id//github/issues`

I was using [koa router](https://github.com/alexmingoia/koa-router) and this worked as expected, but refactoring to react router is causing this issue. Can this be fixed, or is there a way to disable what looks like `decodeURI` in step 4? I cannot get my original id back.

**Comment by timdorr** [comment] 2017-08-28 13:20
Related to #5474.
Duplicate of ReactTraining/history#505.

**Closed by timdorr** 2017-08-28 13:20 UTC
