### ISSUE TITLE
Wrong internal dependency tree for beta versions

### ISSUE THREAD

**Issue by Aprillion** [ReactTraining/react-router#4680] opened 2017-03-10 13:21 UTC
## Version
4.0.0-beta.7 (or any 4.x version lower than the current `@next`)

## Steps to reproduce

1. in `package.json` of an actual project, use an exact-version dependency, e.g. `"react-router-dom": "4.0.0-beta.7"`
2. wait until a newer version is released, beta.8, before installing (e.g. when continuous integration runs `npm install` without recycling node_modules)
3. run `npm install`

## Expected Behavior

```
├─┬ react-router-dom@4.0.0-beta.7 
│ ├─┬ ...
│ └── react-router@4.0.0-beta.7
```

No runtime errors.

## Actual Behavior

Wrong dependency to beta.8:
```
├─┬ react-router-dom@4.0.0-beta.7 
│ ├─┬ history@4.6.0 
│ │ ├── resolve-pathname@2.0.2 
│ │ ├── value-equal@0.2.0 
│ │ └── warning@3.0.0 
│ └── react-router@4.0.0-beta.8 
```

Random runtime errors, nothing is rendered, e.g.:
```
Uncaught TypeError: Cannot read property 'path' of undefined
    at Switch.js:53
    at forEachSingleChild (ReactChildren.js:51)
    at traverseAllChildrenImpl (traverseAllChildren.js:77)
    at traverseAllChildrenImpl (traverseAllChildren.js:93)
    at traverseAllChildren (traverseAllChildren.js:172)
    at Object.forEachChildren [as forEach] (ReactChildren.js:71)
    at Switch.render (Switch.js:51)
    at ReactCompositeComponent.js:796
    at measureLifeCyclePerf (ReactCompositeComponent.js:75)
    at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext (ReactCompositeComponent.js:795)
```

**Comment by Aprillion** [comment] 2017-03-10 13:34
workaround:
```
  "dependencies": {
    "react-router": "4.0.0-beta.7",
    "react-router-dom": "4.0.0-beta.7",
  },
```

will install correctly:
```
├─┬ react-router@4.0.0-beta.7 
│ ├─┬ history@4.6.0 
│ │ ├── resolve-pathname@2.0.2 
│ │ └── value-equal@0.2.0 
│ └── warning@3.0.0 
├── react-router-dom@4.0.0-beta.7 
```

**Comment by timdorr** [comment] 2017-03-10 14:04
Dupe of #4656

**Closed by timdorr** 2017-03-10 14:04 UTC
