### ISSUE TITLE
Allow an array to be passed to Route.path

### ISSUE THREAD

**Issue by stickfigure** [ReactTraining/react-router#4844] opened 2017-03-27 02:12 UTC
The react-router docs say that `Route.path` can be "Any valid URL path that path-to-regexp understands." According to the [path-to-regexp docs](https://www.npmjs.com/package/path-to-regexp), this includes an array of strings.

Passing an array of strings produces this error: `Failed prop type: Invalid prop 'path' of type 'array' supplied toRoute, expected 'string'.`

As a workaround, a regex can be passed in eg `(/path1|/path2|/path3)` but this is awkward. The use case is to allow multiple paths to cause a link to render as active.

**Comment by timdorr** [comment] 2017-03-27 03:21
Dupe of #4551.

**Closed by timdorr** 2017-03-27 03:21 UTC
