### ISSUE TITLE
Browsers' back and forward button make a connected component rerender  

### ISSUE THREAD

**Issue by wayweary** [ReactTraining/react-router#6049] opened 2018-03-30 00:47 UTC
React router redux

2 container routes both connected and subscribing only to the router redux reducer. hostname/route1/ and hostname/route2

1. **Going to route2**: Go from route1 to route2 via a **Link Component**. route1 is **not** re-rendered which i expect. 
2. **Going back to route1**: Click **browsers back button**, route2 will then first be re-rendered then route1. I i would expect it to work similar to clicking a react router dom link component, ie only route1 would be rendered in this case.
3. **Going forward to route2**: Click **browsers forward button**, similar situation as in nr 2 above.

Are these behaviours intended? 

I would have expected the browsers back/forward button to only trigger the container we are going to not the one we are leaving.

**Comment by timdorr** [comment] 2018-03-30 12:03
An example of what you're seeing is really necessary here. But there are known issues with double-rendering right now. Hence the alpha status.

**Comment by wayweary** [comment] 2018-03-30 12:50
Hi, thanks for quick reply. Just wanted to make sure this was a bug and not intended.
I made up a sandbox of what i see in my project here https://codesandbox.io/s/8yv7p018rl 
Then follow this:
1. Only use the environment inside codesandbox (my other project is not in codesandbox though), i mean, dont open the example in another tab.
2. Open code sandbox's console and the live view
3. Click Page 1 
4. Click codesandboxes' liveviews' backbutton
 . What happens: Both Page1 (Route1) and Home component will render (viewing the logs in each render)
 . What i guess is expected: Only Home component should make a render
5. Using the forward button has the same behavior
6. Only navigating using the Link components works great

**Comment by pdme** [comment] 2018-04-03 14:00
+1

**Comment by zzzgit** [comment] 2018-04-26 10:38
where is the `liveviews` button?

**Comment by mahesh-beehively** [comment] 2018-04-27 17:57
Do we any update/fix for the same?

**Comment by mahesh-beehively** [comment] 2018-04-28 19:01
@timdorr any specific reason for deleting the comments? Looks like you want to hide your failure from the world! 
This type of nature will encourage the people to fork the repo. and maintain their own copy instead of contributing to original and that will the defeat the purpose of opensource!

**Comment by mahesh-beehively** [comment] 2018-04-29 03:10
Agreed. 
But, even if those comments are constructive they will reveal the desire to fix the issue and may encourage someone to contribute a fix!

**Comment by E-Kuerschner** [comment] 2018-05-22 18:58
I've come across this issue as well.
Using: `react-router-dom@4.2.2 react-router-redux@5.0.0-alpha.9`

Basically in the exact same situation as @wayweary.
To maybe add more background into the mix, I have noticed that the undesired rerender occurs before the `LOCATION_CHANGE` action is emitted by the `react-router-redux` middleware - due to a change in the `router.location.pathname` state which the connected component observes.

What I have observed is this: 
1. Click back in browser
2. address bar changes to previous page's pathname
3. current connected component rerenders
4. a `LOCATION_CHANGE` is dispatched with the new pathname

**Comment by technicallyfeasible** [comment] 2018-05-25 08:43
I am having a similar issue. The problem is compounded by the fact that the previous component rerenders with the new (!) location.
I would expect a component added to a route to never render on the wrong location since it generates issues with loading data, especially since we are using query parameters in the url for state management.

**Comment by timdorr** [comment] 2018-06-06 16:04
Closing this out since react-router-redux is deprecated. Use [connected-react-router](https://github.com/supasate/connected-react-router) instead!

**Closed by timdorr** 2018-06-06 16:04 UTC

**Comment by technicallyfeasible** [comment] 2018-06-07 06:33
so sad to see this closed since connected-react-router only works with v4
