### ISSUE TITLE
Docs: layout breaks

### ISSUE THREAD

**Issue by jacklaurencegaray** [ReactTraining/react-router#6974] opened 2019-10-07 08:30 UTC
Hi, this isn't really a bug report or anything significant, just a little bit of layout problem on the docs

Docs link:
https://reacttraining.com/react-router/web/api/Hooks/uselocation

Preview:
https://prnt.sc/pfuna0

**Comment by pshrmn** [comment] 2019-10-07 14:14
This would be a good first PR for someone.

This is caused by the long `react-router-dom` import string. The simple fix would be for us to split those imports across lines.

The problem should be fixed for both `useLocation` and `useParams`.

The source for the hooks documentation is [this file](https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/api/hooks.md).

```jsx
import {
  BrowserRouter as Router,
  Switch,
  useLocation
} from "react-router"
```

**Closed** 2019-10-07 14:28 UTC
