### ISSUE TITLE
[v6] Hooks cause rerender even if nothing has changed

### ISSUE THREAD

**Issue by benneq** [ReactTraining/react-router#7667] opened 2020-10-23 13:19 UTC
## Version

`6.0.0-beta.0`

## Test Case

https://codesandbox.io/s/react-router-forked-ef2vs?file=/index.js

## Steps to reproduce

Click the Button and watch the counter increase

## Expected Behavior

useParams should not return a new instance if params didn't change

## Actual Behavior

useParams always returns a new value

( I'm pretty sure the same behavior applies to other hooks as well. )

**Comment by gdelmas** [comment] 2020-11-03 18:03
for the `useParams` hook this is a duplicate of https://github.com/ReactTraining/react-router/issues/7318

**Comment by timdorr** [comment] 2020-11-03 20:00
Your use effect dependency should be `params.foo`, not the entire `params` object.

**Closed by timdorr** 2020-11-03 20:00 UTC

**Comment by Sandx3** [comment] 2022-02-08 17:39
Any solutions on that? I have a similar issue - my app is getting laggy because of the amount of re-renders caused by useParams new instance

**Comment by naivefun** [comment] 2022-08-19 09:31
> Your use effect dependency should be `params.foo`, not the entire `params` object.

that changes useEffect, however the component still re-rendered. And the reason is react-router context is changed, though effect will not be triggered.

https://codesandbox.io/s/react-router-forked-cwmtid
