### ISSUE TITLE
The location of the <Redirect/> will result in error( Maximum update depth exceeded)

### ISSUE THREAD

**Issue by WormGirl** [ReactTraining/react-router#6748] opened 2019-05-16 10:05 UTC
## Version

**"react": "^16.8.6","react-dom": "^16.8.6","react-router-dom": "^5.0.0",

## Test Case
[correct one](https://codesandbox.io/s/react-router-basic-l8tjj)
[incorrect one](https://codesandbox.io/s/react-router-basic-q52q5)
> Just look the example.js
## Steps to reproduce
Just change the loacation of line 28 and line 29 in example.js , the error will occur.
## Expected Behavior
The demo in official document about Redirect is actually wrong.The two sentences in the picture need to be exchanged, otherwise an error will be reported(Maximum update depth exceeded).
![image](https://user-images.githubusercontent.com/16078260/57845448-9e25f200-7804-11e9-93b3-9415077cda6f.png)
in my project throw this error:
![image](https://user-images.githubusercontent.com/16078260/57846267-69b33580-7806-11e9-89c9-ac094b8a0075.png)
## Actual Behavior
Throw an  error, Maximum update depth exceeded. I think if this not an  error, The docs need to update, And this order needs to be emphasized in the docs, otherwise it is difficult to understand

**Comment by MeiKatz** [comment] 2019-05-16 10:27
That's definitely not the expected behaviour. I will have a look and will fix this.

**Comment by StringEpsilon** [comment] 2019-05-16 15:54
I'm reasonably sure that this is another manifestation of #6673 and should be fixed by 5.0.1.

In the meantime: 

@WormGirl You run into this bug, because your Redirect `from` always matches, because `/users/profile` matches for `/user/:id`.

The easiest fix to to simply add 'exact' to the Redirect:

```jsx
<Redirect from="/" exact to="/about" />
```

See this fork of your codesandbox:

https://codesandbox.io/s/react-router-basic-cro61

**Comment by timdorr** [comment] 2019-05-16 16:48
Yep, this is already fixed by #6673. I hope to have a release out soon.

**Closed by timdorr** 2019-05-16 16:48 UTC

**Comment by alexkrolick** [comment] 2019-05-21 04:03
`<Redirect exact />` still triggers the recursion if the from route is inside an inexact match. For example, when redirecting from a root path to a deeper path (`/me` -> `/me/home`)

**Comment by WormGirl** [comment] 2019-05-21 07:32
> `<Redirect exact />` still triggers the recursion if the from route is inside an inexact match. For example, when redirecting from a root path to a deeper path (`/me` -> `/me/home`)
> 
> EDIT: I didn't test the master branch, this was a comment about the workaround suggested for 5.0.0

As @StringEpsilon  said, this bug will be fixed in 5.0.1
