### ISSUE TITLE
Support a function for Prompt's when prop

### ISSUE THREAD

**Issue by Aaronius** [ReactTraining/react-router#5573] opened 2017-09-28 18:54 UTC
Would you be opposed to supporting a function for Prompt's `when` prop? Right now it only supports a boolean value. My use case is that in order to determine the boolean I have to run some more expensive calculations that I would rather not be doing on every render. If I provided a function, I would hope it would only be called on a navigation attempt.

By looking at the source code for Prompt, it seems like this would be possible by leveraging the underlying `history.block`'s function support:

`history.block((location, action) => { ... })`

We would essentially use that to wrap whatever function (or boolean) the consumer passes in.

If this seems like a legit thing to do, let me know and I can take a stab at implementation.

**Comment by timdorr** [comment] 2017-09-28 19:02
Dupe of #4743.

**Closed by timdorr** 2017-09-28 19:02 UTC

**Comment by Aaronius** [comment] 2017-09-28 19:27
I should've looked at closed issues. Thanks!
