### ISSUE TITLE
Path matching with basename has false positives

### ISSUE THREAD

**Issue by lhorie** [ReactTraining/react-router#5199] opened 2017-06-02 16:40 UTC
## Version
4.1.1

## Test Case

```sh
# in terminal
npm install -g create-react-app
create-react-app basename-squashing
cd basename-squashing
npm install react-router react-router-dom --save
npm start
```

```js
// index.js
import React from 'react';
import ReactDOM from 'react-dom';
import { Router, Route, Switch } from 'react-router'
import { Link, BrowserRouter } from 'react-router-dom'

var MainLayout = function() {
  return (
    <BrowserRouter basename="/a">
      <div>
        <ul>
          <li><a href="/x">&lt;a&gt; to x</a></li>
          <li><a href="/y">&lt;a&gt; to y</a></li>
          <li><a href="/a/x">&lt;a&gt; to /a/x</a></li>
          <li><a href="/a/y">&lt;a&gt; to /a/y</a></li>
          <li><Link to="/x">&lt;Link&gt; to x</Link></li>
          <li><Link to="/y">&lt;Link&gt; to y</Link></li>
          <li><a href="/z">&lt;a&gt; to non-existent route</a></li>
          <li><Link to="/z">&lt;Link&gt; to non-existent route</Link></li>
        </ul>
        <hr />
        <Switch>
          <Route exact path="/x"><div>Page x</div></Route>
          <Route exact path="/y"><div>Page y</div></Route>
          <Route><div>Not found</div></Route>
        </Switch>
      </div>
    </BrowserRouter>
  )
}

ReactDOM.render(<MainLayout />, document.getElementById('root'))
```

## Steps to reproduce

Click links. Bottom area under `<hr>` should change accordingly

## Expected Behavior

Clicking the links in order should show respectively:

- Not found
- Not found
- Page x
- Page y
- Page x
- Page y
- Not found
- Not found

## Actual Behavior

Clicking the links in order shows respectively:

- Page x
- Page y
- Page x
- Page y
- Page x
- Page y
- Not found
- Not found

`<a href="/x"></a>` should not match `<Route exact path="/x"></Route>` because there's a `basename` in `BrowserRouter`. Instead, it should match `<Route><div>Not found</div></Route>`

**Comment by pshrmn** [comment] 2017-06-02 19:05
So the first problem with your setup is that while you are specifying a `basename`, that doesn't always exist. The `basename` should only be use for projects that aren't served from the root, which is what the `create-react-app` app does. I'm sure that there is a way to configure the app to do this, but I'm not familiar enough with `create-react-app` to know offhand.

When `history` parses a URL, it strips the `basename` off of the `window.location.pathname` and only uses the remainder. This means that a `pathname` that does not begin with the `basename` is treated the same as one that does not. This is obviously a problem.

The good news is that this has already been addressed in https://github.com/ReactTraining/history/pull/453 by adding a warning when you attempt to use a `basename` on a page whose `pathname` does not begin with the `basename`. The bad news is that there has not been a release of `history` since that was merged.

I'm going to close this because this is mostly just an issue that needs a new `history` release to show what the problem is and isn't directly a React Router issue. If there is anything that you think I failed to address, I can take another look, but I think that the above sufficiently explains what is happening.

**Closed by pshrmn** 2017-06-02 19:05 UTC
