### ISSUE TITLE
Uncaught TypeError: Cannot read property 'propTypes' of undefined

### ISSUE THREAD

**Issue by fff2139678** [ReactTraining/react-router#6658] opened 2019-03-22 08:57 UTC
## Version

react-router: 5.0.0
react-router-dom: 5.0.0

## Application tests are failing with this error:

react-router-dom.js:278 Uncaught TypeError: Cannot read property 'propTypes' of undefined
at eval (react-router-dom.js:278)
at Module../node_modules/_react-router-dom@5.0.0@react-router-dom/esm/react-router-dom.js (app.js:4830)

**Comment by timdorr** [comment] 2019-03-22 11:43
Dupe of #6630. You have mixed versions of react-router and react-router-dom installed.

**Closed by timdorr** 2019-03-22 11:43 UTC
