### ISSUE TITLE
Broken Links on react-router.com

### ISSUE THREAD

**Issue by sauravkhdoolia** [ReactTraining/react-router#7484] opened 2020-07-05 09:56 UTC
## ^5.1

**This Error is in the docs website.**

## Test Case

Go to [React Router's This page](https://reactrouter.com/web/api/Hooks/)

## Steps to reproduce
Click on any link in there such as Hooks, useParams etc.

## Expected Behavior
Should scroll down to the heading level clicked.

## Actual Behavior
Takes to the homepage.

## The Problem
Anchor tags of website are still being made from react-router/docs folder, and they have /react-router/ in front of them.
Example Link from prod site: `https://reactrouter.com/react-router/web/api/Hooks/usehistory`.
I think react-router's website used to be react-training.com, and the links are the same.

I'd love to open a PR and contribute, But i seriously have no idea where those links are being built.

**Comment by pReya** [comment] 2020-07-09 10:49
There is a `<DelegateMarkdownLinks>` component, which removes the basepath from all the markdown links and converts them to proper links. So this should all be fixed by correctly setting the basepath, which is added into the `<base>` tag during compile time by webpack. Webpack takes it from the `webpack.config.js` (Link: https://github.com/ReactTraining/react-router/blob/f6d98ecd98f97e729d09f17dff8e0dc4c92d2f5b/website/webpack.config.js#L19). Unfortunately I can't build the site locally for some reason, to test if this really fixes it, so I am not submitting a untested PR.

**Comment by ptolemybarnes** [comment] 2020-07-21 13:07
💯  Would be nice if those links worked!

**Comment by morgan-sam** [comment] 2020-08-10 22:25
Currently working on this one. The links work as expected locally, not sure why.

**Comment by morgan-sam** [comment] 2020-08-14 16:32
@pReya Changing the publicPath is giving me a CORB error with no webpage displayed. However I noticed when changing the publicPath to `https://reactrouter.com/` the page icons correctly display even though the page doesn't load, which leads me to think it would work in production.

I changed the publicPath to `process.env.NODE_ENV === 'production' ? 'https://reactrouter.com' : '/'` but I don't know how to test if this will actually work. Does anyone know how to test this?

**Comment by togakangaroo** [comment] 2020-09-17 21:14
I love yall, and react router does good work, but damn if all internal links on react router's docs being broken due to a react router error isn't a very funny joke

**Comment by Flandre-X** [comment] 2020-10-11 16:36
Could it be that the bug is caused by `webpack/markdown-loader.js`? Perhaps `correctLinks()` or its caller?

**Comment by pReya** [comment] 2020-10-15 18:57
Looked into this a little more. It seems that somebody already fixed the code (https://github.com/ReactTraining/react-router/issues/7540), but since then the page hasn't been re-reployed, yet. So I think all it would take to fix this is have someone with the proper rights kick off a new deployment. Is this correct @timdorr? Who has the rights to deploy the page? @ryanflorence @mjackson maybe you can help?

**Comment by timdorr** [comment] 2020-11-05 02:11
I was finally able to get some time to update the website branch. This appears to be fixed. I'll close this out, but let me know if I missed something!

**Closed by timdorr** 2020-11-05 02:11 UTC

**Comment by jashatton** [comment] 2021-08-16 19:21
The links appear broke again on the documentation site.  I noticed this last week but, waited to see if it would start working.  Bumping this issue, but can open an new one if preferred.

**Comment by KorayAydemir** [comment] 2021-10-10 20:46
Docs has been completely broken for a long time now. Have the support for react router stopped ?

**Comment by timdorr** [comment] 2021-10-11 00:28
@KorayAydemir Nope, we're still here and the site is working fine for me. In fact, development has picked back up significantly in the past few months. Might be something with your ISP or firewall blocking the site.
