### ISSUE TITLE
onEnter called twice 3.0.0

### ISSUE THREAD

**Issue by pvorona** [ReactTraining/react-router#4304] opened 2016-12-25 21:33 UTC
I've got 2 `<Route />` (a, b) with async onEnter hooks, they are called twice when i click on `<Link />` (in stack trace first run is caused by handleClick, second by handleHashChange)

3.0.0

## Expected Behavior
onEnter called once

**Comment by timdorr** [comment] 2016-12-26 04:23
Dupe of #3220.

**Closed by timdorr** 2016-12-26 04:23 UTC
