### ISSUE TITLE
[Docs] Upgrading to v3.0.0

### ISSUE THREAD

**Issue by ncphillips** [ReactTraining/react-router#4205] opened 2016-11-18 15:06 UTC
I just noticed that the docs are lacking an upgrade guide for v3.0.0. 

I'm looking forward to upgrading, but it would be great if this could be made available first.

**Comment by timdorr** [comment] 2016-11-18 18:51
Dupe of #4174, #4192, and #4175. Please search before posting a new issue.

**Closed by timdorr** 2016-11-18 18:51 UTC

**Comment by ncphillips** [comment] 2016-11-18 19:08
Sorry :( I tried searching, but apparently ineffectively
